// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/rpcEvent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HopNodeClient is the client API for HopNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HopNodeClient interface {
	ProcessRequest(ctx context.Context, in *TrxReq, opts ...grpc.CallOption) (*TrxRes, error)
	ProcessHop(ctx context.Context, in *TrxReq, opts ...grpc.CallOption) (*TrxRes, error)
	EndHop(ctx context.Context, in *TrxInfo, opts ...grpc.CallOption) (*Empty, error)
	EndTx(ctx context.Context, in *TxRWSets, opts ...grpc.CallOption) (*Empty, error)
	Unlock(ctx context.Context, in *TxRWSets, opts ...grpc.CallOption) (*Empty, error)
	Prepare(ctx context.Context, in *TxRWSets, opts ...grpc.CallOption) (*Empty, error)
	Pull(ctx context.Context, in *IdList, opts ...grpc.CallOption) (*History, error)
	Tick(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Tok(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stat, error)
}

type hopNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewHopNodeClient(cc grpc.ClientConnInterface) HopNodeClient {
	return &hopNodeClient{cc}
}

func (c *hopNodeClient) ProcessRequest(ctx context.Context, in *TrxReq, opts ...grpc.CallOption) (*TrxRes, error) {
	out := new(TrxRes)
	err := c.cc.Invoke(ctx, "/proto.HopNode/ProcessRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopNodeClient) ProcessHop(ctx context.Context, in *TrxReq, opts ...grpc.CallOption) (*TrxRes, error) {
	out := new(TrxRes)
	err := c.cc.Invoke(ctx, "/proto.HopNode/ProcessHop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopNodeClient) EndHop(ctx context.Context, in *TrxInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.HopNode/EndHop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopNodeClient) EndTx(ctx context.Context, in *TxRWSets, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.HopNode/EndTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopNodeClient) Unlock(ctx context.Context, in *TxRWSets, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.HopNode/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopNodeClient) Prepare(ctx context.Context, in *TxRWSets, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.HopNode/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopNodeClient) Pull(ctx context.Context, in *IdList, opts ...grpc.CallOption) (*History, error) {
	out := new(History)
	err := c.cc.Invoke(ctx, "/proto.HopNode/Pull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopNodeClient) Tick(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.HopNode/Tick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopNodeClient) Tok(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.HopNode/Tok", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hopNodeClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stat, error) {
	out := new(Stat)
	err := c.cc.Invoke(ctx, "/proto.HopNode/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HopNodeServer is the server API for HopNode service.
// All implementations must embed UnimplementedHopNodeServer
// for forward compatibility
type HopNodeServer interface {
	ProcessRequest(context.Context, *TrxReq) (*TrxRes, error)
	ProcessHop(context.Context, *TrxReq) (*TrxRes, error)
	EndHop(context.Context, *TrxInfo) (*Empty, error)
	EndTx(context.Context, *TxRWSets) (*Empty, error)
	Unlock(context.Context, *TxRWSets) (*Empty, error)
	Prepare(context.Context, *TxRWSets) (*Empty, error)
	Pull(context.Context, *IdList) (*History, error)
	Tick(context.Context, *Empty) (*Empty, error)
	Tok(context.Context, *Empty) (*Empty, error)
	Shutdown(context.Context, *Empty) (*Stat, error)
	mustEmbedUnimplementedHopNodeServer()
}

// UnimplementedHopNodeServer must be embedded to have forward compatible implementations.
type UnimplementedHopNodeServer struct {
}

func (UnimplementedHopNodeServer) ProcessRequest(context.Context, *TrxReq) (*TrxRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessRequest not implemented")
}
func (UnimplementedHopNodeServer) ProcessHop(context.Context, *TrxReq) (*TrxRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessHop not implemented")
}
func (UnimplementedHopNodeServer) EndHop(context.Context, *TrxInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndHop not implemented")
}
func (UnimplementedHopNodeServer) EndTx(context.Context, *TxRWSets) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndTx not implemented")
}
func (UnimplementedHopNodeServer) Unlock(context.Context, *TxRWSets) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (UnimplementedHopNodeServer) Prepare(context.Context, *TxRWSets) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedHopNodeServer) Pull(context.Context, *IdList) (*History, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedHopNodeServer) Tick(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tick not implemented")
}
func (UnimplementedHopNodeServer) Tok(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tok not implemented")
}
func (UnimplementedHopNodeServer) Shutdown(context.Context, *Empty) (*Stat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedHopNodeServer) mustEmbedUnimplementedHopNodeServer() {}

// UnsafeHopNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HopNodeServer will
// result in compilation errors.
type UnsafeHopNodeServer interface {
	mustEmbedUnimplementedHopNodeServer()
}

func RegisterHopNodeServer(s grpc.ServiceRegistrar, srv HopNodeServer) {
	s.RegisterService(&HopNode_ServiceDesc, srv)
}

func _HopNode_ProcessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).ProcessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/ProcessRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).ProcessRequest(ctx, req.(*TrxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HopNode_ProcessHop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).ProcessHop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/ProcessHop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).ProcessHop(ctx, req.(*TrxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HopNode_EndHop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrxInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).EndHop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/EndHop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).EndHop(ctx, req.(*TrxInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _HopNode_EndTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRWSets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).EndTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/EndTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).EndTx(ctx, req.(*TxRWSets))
	}
	return interceptor(ctx, in, info, handler)
}

func _HopNode_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRWSets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).Unlock(ctx, req.(*TxRWSets))
	}
	return interceptor(ctx, in, info, handler)
}

func _HopNode_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRWSets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).Prepare(ctx, req.(*TxRWSets))
	}
	return interceptor(ctx, in, info, handler)
}

func _HopNode_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).Pull(ctx, req.(*IdList))
	}
	return interceptor(ctx, in, info, handler)
}

func _HopNode_Tick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).Tick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/Tick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).Tick(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HopNode_Tok_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).Tok(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/Tok",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).Tok(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HopNode_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HopNodeServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HopNode/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HopNodeServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HopNode_ServiceDesc is the grpc.ServiceDesc for HopNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HopNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HopNode",
	HandlerType: (*HopNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessRequest",
			Handler:    _HopNode_ProcessRequest_Handler,
		},
		{
			MethodName: "ProcessHop",
			Handler:    _HopNode_ProcessHop_Handler,
		},
		{
			MethodName: "EndHop",
			Handler:    _HopNode_EndHop_Handler,
		},
		{
			MethodName: "EndTx",
			Handler:    _HopNode_EndTx_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _HopNode_Unlock_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _HopNode_Prepare_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _HopNode_Pull_Handler,
		},
		{
			MethodName: "Tick",
			Handler:    _HopNode_Tick_Handler,
		},
		{
			MethodName: "Tok",
			Handler:    _HopNode_Tok_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _HopNode_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpcEvent.proto",
}
