use crate::cfg::{self, PrimitiveType, Type, TypeId};
use std::error::Error;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// Generate the `global.go` file inside `<output>/go/`.
pub fn generate_global(
    program: &cfg::Program,
    output_dir: &Path,
) -> Result<PathBuf, Box<dyn Error>> {
    // Ensure base directory exists
    fs::create_dir_all(output_dir)?;

    let go_dir = output_dir.join("go");
    if go_dir.exists() {
        fs::remove_dir_all(&go_dir)?;
    }
    fs::create_dir_all(&go_dir)?;

    let file_path = go_dir.join("global.go");
    let mut file = fs::File::create(&file_path)?;

    let source = build_global_source(program);
    file.write_all(source.as_bytes())?;

    Ok(file_path)
}

fn build_global_source(program: &cfg::Program) -> String {
    let mut out = String::new();

    out.push_str("// Code generated by FMitF Go code generator. DO NOT EDIT.\n\n");
    out.push_str("package chainManager\n\n");
    out.push_str("import (\n");
    out.push_str("\t\"encoding/json\"\n");
    out.push_str("\t\"github.com/boltdb/bolt\"\n");
    out.push_str(")\n\n");

    // Shared helpers expected by generated hops.
    out.push_str("func mustJSON(value any) []byte {\n");
    out.push_str("\tbytes, err := json.Marshal(value)\n");
    out.push_str("\tif err != nil {\n");
    out.push_str("\t\tpanic(err)\n");
    out.push_str("\t}\n");
    out.push_str("\treturn bytes\n");
    out.push_str("}\n\n");

    out.push_str("func putData(bucket *bolt.Bucket, key []byte, value []byte) {\n");
    out.push_str("\tif bucket == nil {\n");
    out.push_str("\t\tpanic(\"nil bucket\")\n");
    out.push_str("\t}\n");
    out.push_str("\tif err := bucket.Put(key, value); err != nil {\n");
    out.push_str("\t\tpanic(err)\n");
    out.push_str("\t}\n");
    out.push_str("}\n\n");

    for table_id in &program.all_tables {
        let table = &program.tables[*table_id];
        let struct_name = go_type_name(&table.name);
        let key_struct_name = format!("{}Key", struct_name);
        let bucket_name = format!("t{}", struct_name);

        // Key struct
        out.push_str(&format!("type {} struct {{\n", key_struct_name));
        for field_id in &table.primary_key_fields {
            let field = &program.table_fields[*field_id];
            let go_field_name = go_field_name(&field.name);
            let go_type = go_type_for_field(program, field.field_type, true);
            out.push_str(&format!("\t{} {}\n", go_field_name, go_type));
        }
        out.push_str("}\n\n");

        // Row struct
        out.push_str(&format!("type {} struct {{\n", struct_name));
        out.push_str(&format!("\tKey {}\n", key_struct_name));
        for field_id in &table.other_fields {
            let field = &program.table_fields[*field_id];
            let go_field_name = go_field_name(&field.name);
            let go_type = go_type_for_field(program, field.field_type, false);
            out.push_str(&format!("\t{} {}\n", go_field_name, go_type));
        }
        out.push_str("}\n\n");

        // get<Table>
        out.push_str(&format!(
            "func get{}(tx *bolt.Tx, key {}) ([]byte, {}) {{\n",
            struct_name, key_struct_name, struct_name
        ));
        out.push_str(&format!(
            "\tbucket := tx.Bucket([]byte(\"{}\"))\n",
            bucket_name
        ));
        out.push_str("\tif bucket == nil {\n");
        out.push_str(&format!("\t\tpanic(\"missing bucket {}\")\n", bucket_name));
        out.push_str("\t}\n");
        out.push_str("\tkeyBytes := mustJSON(key)\n");
        out.push_str(&format!("\tvar row {}\n", struct_name));
        out.push_str("\tif data := bucket.Get(keyBytes); data != nil {\n");
        out.push_str("\t\tif err := json.Unmarshal(data, &row); err != nil {\n");
        out.push_str("\t\t\tpanic(err)\n");
        out.push_str("\t\t}\n");
        out.push_str("\t}\n");
        out.push_str("\trow.Key = key\n");
        out.push_str("\treturn keyBytes, row\n");
        out.push_str("}\n\n");

        // put<Table>
        out.push_str(&format!(
            "func put{}(tx *bolt.Tx, key {}, row {}) {{\n",
            struct_name, key_struct_name, struct_name
        ));
        out.push_str(&format!(
            "\tbucket := tx.Bucket([]byte(\"{}\"))\n",
            bucket_name
        ));
        out.push_str("\tif bucket == nil {\n");
        out.push_str(&format!("\t\tpanic(\"missing bucket {}\")\n", bucket_name));
        out.push_str("\t}\n");
        out.push_str("\trow.Key = key\n");
        out.push_str("\tputData(bucket, mustJSON(key), mustJSON(row))\n");
        out.push_str("}\n\n");
    }

    out
}

fn go_type_for_field(program: &cfg::Program, ty_id: TypeId, _is_primary_key: bool) -> String {
    match &program.types[ty_id] {
        Type::Primitive(PrimitiveType::Int) => "uint64".to_string(),
        Type::Primitive(PrimitiveType::Float) => "float32".to_string(),
        Type::Primitive(PrimitiveType::Bool) => "bool".to_string(),
        Type::Primitive(PrimitiveType::String) => "string".to_string(),
        other => panic!("Unsupported field type in Go codegen: {:?}", other),
    }
}

fn go_type_name(name: &str) -> String {
    name.split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => {
                    let mut s = String::new();
                    s.push(first.to_ascii_uppercase());
                    s.push_str(&chars.as_str().to_ascii_lowercase());
                    s
                }
                None => String::new(),
            }
        })
        .collect::<String>()
}

fn go_field_name(name: &str) -> String {
    // Field identifiers can remain as-is as they are already exported (upper-case)
    name.to_string()
}
