use crate::cfg::{self, PrimitiveType, Type, TypeId, VariableId};
use std::fmt::Write;

/// Append the standard generated Go file header and import block.
pub fn write_go_file_header(out: &mut String, imports: &[&str]) -> Result<(), std::fmt::Error> {
    writeln!(
        out,
        "// Code generated by FMitF Go code generator. DO NOT EDIT."
    )?;
    writeln!(out)?;
    writeln!(out, "package chainManager")?;

    if !imports.is_empty() {
        writeln!(out)?;
        writeln!(out, "import (")?;
        for entry in imports {
            writeln!(out, "\t\"{}\"", entry)?;
        }
        writeln!(out, ")")?;
    }

    writeln!(out)?;
    Ok(())
}

/// Convert an identifier to PascalCase suitable for exported Go symbols.
pub fn pascal_case(name: &str) -> String {
    name.split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => {
                    let mut s = String::new();
                    s.push(first.to_ascii_uppercase());
                    s.push_str(&chars.as_str().to_ascii_lowercase());
                    s
                }
                None => String::new(),
            }
        })
        .collect::<String>()
}

/// Convert an identifier to snake_case.
pub fn snake_case(name: &str) -> String {
    name.split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| segment.to_ascii_lowercase())
        .collect::<Vec<_>>()
        .join("_")
}

/// Get Go type string for a CFG type
pub fn go_type_string(program: &cfg::Program, ty_id: TypeId) -> String {
    match &program.types[ty_id] {
        Type::Primitive(PrimitiveType::Int) => "uint64".to_string(),
        Type::Primitive(PrimitiveType::Float) => "float32".to_string(),
        Type::Primitive(PrimitiveType::Bool) => "bool".to_string(),
        Type::Primitive(PrimitiveType::String) => "string".to_string(),
        Type::List(inner_ty) => {
            format!("[]{}", go_type_string(program, *inner_ty))
        }
        Type::Row { table_id } => {
            // Row<T> type should be just T in Go
            let table = &program.tables[*table_id];
            pascal_case(&table.name)
        }
        Type::Declared { type_id, .. } => {
            let user_type = &program.user_defined_types[*type_id];
            if user_type.name == "unit" {
                "Unit".to_string()
            } else if user_type.name == "UUID" {
                "UUID".to_string()
            } else if user_type.name == "Iterator" {
                // Handle Iterator<T> type - in Go we use *Iterator for all iterators
                "*Iterator".to_string()
            } else {
                format!(
                    "/* Unsupported user type {} */ interface{{}}",
                    user_type.name
                )
            }
        }
        //TODO: Implement support for other types
        //other => panic!("Unsupported type in Go codegen: {:?}", other),
        other => format!("/* Unsupported type */ interface{{}} /* {:?} */", other),
    }
}

/// Get the Go variable name for a CFG variable
pub fn go_var_name(program: &cfg::Program, var_id: VariableId) -> String {
    let var = &program.variables[var_id];
    let name = &var.name;

    // Sanitize variable names - replace # with underscore
    name.replace('#', "_")
}
