// Code generated by FMitF Go code generator. DO NOT EDIT.

package chainManager

import (
	"strconv"
	"encoding/json"
	"github.com/boltdb/bolt"
)

// TODO: Add composite/list converters and handle locale or precision policies if required.

// UUID is a unique identifier type (uint64 for now)
type UUID uint64

// genUUID generates a unique identifier
// In a real implementation, this should generate proper UUIDs
// For now, it returns a simple counter-based ID
var uuidCounter uint64 = 1
func genUUID(n int, m int) UUID {
	_ = n
	_ = m
	uuidCounter++
	return UUID(uuidCounter)
}

// Unit is a user-defined type representing the unit type
type Unit struct {}

// to_unit converts any value to Unit type (pass-by-reference style)
func to_unit[T any](value T, result *Unit) {
	// This function marks the value as used and assigns to result
	_ = value
	*result = Unit{}
}

// toUint64 converts string to uint64
func toUint64(s string) uint64 {
	v, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		panic(err)
	}
	return v
}

// toInt64 converts string to int64
func toInt64(s string) int64 {
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		panic(err)
	}
	return v
}

// toFloat32 converts string to float32
func toFloat32(s string) float32 {
	f, err := strconv.ParseFloat(s, 32)
	if err != nil {
		panic(err)
	}
	return float32(f)
}

// toBool converts string to bool
func toBool(s string) bool {
	b, err := strconv.ParseBool(s)
	if err != nil {
		panic(err)
	}
	return b
}

// fromUint64 converts uint64 to string
func fromUint64(v uint64) string {
	return strconv.FormatUint(v, 10)
}

// fromInt64 converts int64 to string
func fromInt64(v int64) string {
	return strconv.FormatInt(v, 10)
}

// fromFloat32 converts float32 to string
func fromFloat32(f float32) string {
	return strconv.FormatFloat(float64(f), 'f', -1, 32)
}

// fromBool converts bool to string
func fromBool(b bool) string {
	return strconv.FormatBool(b)
}

// concat joins any number of string parts without additional separators.
func concat(parts ...string) string {
	if len(parts) == 0 {
		return ""
	}
	result := parts[0]
	for i := 1; i < len(parts); i++ {
		result += parts[i]
	}
	return result
}

// listGet retrieves an item from a slice, panicking if the index is out of range.
func listGet[T any](list []T, idx int) T {
	if idx < 0 || idx >= len(list) {
		panic("listGet: index out of range")
	}
	return list[idx]
}

// Iterator wraps a BoltDB cursor for table iteration
type Iterator struct {
	cursor *bolt.Cursor
	currentKey []byte
	currentValue []byte
	isValid bool
}

// scan creates an iterator over a table
func scan(tx *bolt.Tx, tableName string, n int, m int) *Iterator {
	_ = n // unused parameters
	_ = m
	b := tx.Bucket([]byte(tableName))
	if b == nil {
		return &Iterator{isValid: false}
	}
	c := b.Cursor()
	k, v := c.First()
	return &Iterator{
		cursor: c,
		currentKey: k,
		currentValue: v,
		isValid: k != nil,
	}
}

// hasNext checks if the iterator has more elements
func hasNext(iter *Iterator) bool {
	return iter.isValid
}

// next advances the iterator to the next element
func next(iter *Iterator) *Iterator {
	if !iter.isValid {
		return iter
	}
	k, v := iter.cursor.Next()
	iter.currentKey = k
	iter.currentValue = v
	iter.isValid = k != nil
	return iter
}

// get_id extracts the UUID from the iterator's current key
// This is a generic implementation that assumes the key is a UUID
func get_id(iter *Iterator) UUID {
	if !iter.isValid {
		panic("get_id: iterator is not valid")
	}
	// Deserialize key as UUID
	var id UUID
	json.Unmarshal(iter.currentKey, &id)
	return id
}
