// Code generated by FMitF Go code generator. DO NOT EDIT.

package chainManager

import (
	"encoding/json"
	"github.com/boltdb/bolt"
	"ShardDB/proto"
	"ShardDB/util"
)

type DeliveryChain struct {
	db   *bolt.DB
	hops []*Hop
}

// DeliveryHop0 lowers hop 0 containing 4 basic block(s).
func DeliveryHop0(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp267 uint64
	var _tmp268 uint64
	var c_id uint64
	var _tmp269 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp271 bool
	var _tmp272 uint64
	var _tmp273 float32
	var _tmp274 float32
	var _tmp275 uint64
	var _tmp276 float32
	var _tmp277 float32
	var _tmp278 float32
	var _tmp279 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB82

BB82:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 0})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp267 = row1.D_NEXT_NO_ID
	no_o_id = _tmp267
	_tmp268 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 0})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp268
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 0}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 0, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp269 = row3.O_C_ID
	c_id = _tmp269
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 0, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 0, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB83
BB83:
	_tmp271 = ol_number < O_OL_CNT
	if _tmp271 {
		goto BB84
	} else {
		goto BB86
	}
BB84:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 0, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp272 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 0, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp273 = float32(_tmp272)
	_tmp274 = ol_total + _tmp273
	ol_total = _tmp274
	_tmp275 = ol_number + 1
	ol_number = _tmp275
	goto BB83
BB86:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp276 = row6.C_BALANCE
	_tmp277 = _tmp276 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp277
	_tmp278 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id}, row7)
	_tmp279 = _tmp278 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp279
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop1 lowers hop 1 containing 4 basic block(s).
func DeliveryHop1(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp280 uint64
	var _tmp281 uint64
	var c_id uint64
	var _tmp282 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp284 bool
	var _tmp285 uint64
	var _tmp286 float32
	var _tmp287 float32
	var _tmp288 uint64
	var _tmp289 float32
	var _tmp290 float32
	var _tmp291 float32
	var _tmp292 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB87

BB87:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 1})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp280 = row1.D_NEXT_NO_ID
	no_o_id = _tmp280
	_tmp281 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 1})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp281
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 1}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 1, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp282 = row3.O_C_ID
	c_id = _tmp282
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 1, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 1, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB88
BB88:
	_tmp284 = ol_number < O_OL_CNT
	if _tmp284 {
		goto BB89
	} else {
		goto BB91
	}
BB89:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 1, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp285 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 1, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp286 = float32(_tmp285)
	_tmp287 = ol_total + _tmp286
	ol_total = _tmp287
	_tmp288 = ol_number + 1
	ol_number = _tmp288
	goto BB88
BB91:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp289 = row6.C_BALANCE
	_tmp290 = _tmp289 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp290
	_tmp291 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id}, row7)
	_tmp292 = _tmp291 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp292
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop2 lowers hop 2 containing 4 basic block(s).
func DeliveryHop2(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp293 uint64
	var _tmp294 uint64
	var c_id uint64
	var _tmp295 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp297 bool
	var _tmp298 uint64
	var _tmp299 float32
	var _tmp300 float32
	var _tmp301 uint64
	var _tmp302 float32
	var _tmp303 float32
	var _tmp304 float32
	var _tmp305 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB92

BB92:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 2})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp293 = row1.D_NEXT_NO_ID
	no_o_id = _tmp293
	_tmp294 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 2})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp294
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 2}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 2, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp295 = row3.O_C_ID
	c_id = _tmp295
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 2, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 2, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB93
BB93:
	_tmp297 = ol_number < O_OL_CNT
	if _tmp297 {
		goto BB94
	} else {
		goto BB96
	}
BB94:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 2, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp298 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 2, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp299 = float32(_tmp298)
	_tmp300 = ol_total + _tmp299
	ol_total = _tmp300
	_tmp301 = ol_number + 1
	ol_number = _tmp301
	goto BB93
BB96:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp302 = row6.C_BALANCE
	_tmp303 = _tmp302 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp303
	_tmp304 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id}, row7)
	_tmp305 = _tmp304 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp305
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop3 lowers hop 3 containing 4 basic block(s).
func DeliveryHop3(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp306 uint64
	var _tmp307 uint64
	var c_id uint64
	var _tmp308 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp310 bool
	var _tmp311 uint64
	var _tmp312 float32
	var _tmp313 float32
	var _tmp314 uint64
	var _tmp315 float32
	var _tmp316 float32
	var _tmp317 float32
	var _tmp318 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB97

BB97:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 3})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp306 = row1.D_NEXT_NO_ID
	no_o_id = _tmp306
	_tmp307 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 3})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp307
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 3}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 3, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp308 = row3.O_C_ID
	c_id = _tmp308
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 3, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 3, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB98
BB98:
	_tmp310 = ol_number < O_OL_CNT
	if _tmp310 {
		goto BB99
	} else {
		goto BB101
	}
BB99:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 3, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp311 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 3, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp312 = float32(_tmp311)
	_tmp313 = ol_total + _tmp312
	ol_total = _tmp313
	_tmp314 = ol_number + 1
	ol_number = _tmp314
	goto BB98
BB101:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp315 = row6.C_BALANCE
	_tmp316 = _tmp315 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp316
	_tmp317 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id}, row7)
	_tmp318 = _tmp317 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp318
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop4 lowers hop 4 containing 4 basic block(s).
func DeliveryHop4(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp319 uint64
	var _tmp320 uint64
	var c_id uint64
	var _tmp321 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp323 bool
	var _tmp324 uint64
	var _tmp325 float32
	var _tmp326 float32
	var _tmp327 uint64
	var _tmp328 float32
	var _tmp329 float32
	var _tmp330 float32
	var _tmp331 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB102

BB102:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 4})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp319 = row1.D_NEXT_NO_ID
	no_o_id = _tmp319
	_tmp320 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 4})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp320
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 4}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 4, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp321 = row3.O_C_ID
	c_id = _tmp321
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 4, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 4, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB103
BB103:
	_tmp323 = ol_number < O_OL_CNT
	if _tmp323 {
		goto BB104
	} else {
		goto BB106
	}
BB104:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 4, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp324 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 4, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp325 = float32(_tmp324)
	_tmp326 = ol_total + _tmp325
	ol_total = _tmp326
	_tmp327 = ol_number + 1
	ol_number = _tmp327
	goto BB103
BB106:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp328 = row6.C_BALANCE
	_tmp329 = _tmp328 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp329
	_tmp330 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id}, row7)
	_tmp331 = _tmp330 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp331
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop5 lowers hop 5 containing 4 basic block(s).
func DeliveryHop5(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp332 uint64
	var _tmp333 uint64
	var c_id uint64
	var _tmp334 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp336 bool
	var _tmp337 uint64
	var _tmp338 float32
	var _tmp339 float32
	var _tmp340 uint64
	var _tmp341 float32
	var _tmp342 float32
	var _tmp343 float32
	var _tmp344 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB107

BB107:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 5})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp332 = row1.D_NEXT_NO_ID
	no_o_id = _tmp332
	_tmp333 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 5})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp333
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 5}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 5, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp334 = row3.O_C_ID
	c_id = _tmp334
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 5, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 5, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB108
BB108:
	_tmp336 = ol_number < O_OL_CNT
	if _tmp336 {
		goto BB109
	} else {
		goto BB111
	}
BB109:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 5, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp337 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 5, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp338 = float32(_tmp337)
	_tmp339 = ol_total + _tmp338
	ol_total = _tmp339
	_tmp340 = ol_number + 1
	ol_number = _tmp340
	goto BB108
BB111:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp341 = row6.C_BALANCE
	_tmp342 = _tmp341 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp342
	_tmp343 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id}, row7)
	_tmp344 = _tmp343 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp344
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop6 lowers hop 6 containing 4 basic block(s).
func DeliveryHop6(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp345 uint64
	var _tmp346 uint64
	var c_id uint64
	var _tmp347 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp349 bool
	var _tmp350 uint64
	var _tmp351 float32
	var _tmp352 float32
	var _tmp353 uint64
	var _tmp354 float32
	var _tmp355 float32
	var _tmp356 float32
	var _tmp357 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB112

BB112:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 6})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp345 = row1.D_NEXT_NO_ID
	no_o_id = _tmp345
	_tmp346 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 6})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp346
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 6}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 6, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp347 = row3.O_C_ID
	c_id = _tmp347
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 6, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 6, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB113
BB113:
	_tmp349 = ol_number < O_OL_CNT
	if _tmp349 {
		goto BB114
	} else {
		goto BB116
	}
BB114:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 6, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp350 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 6, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp351 = float32(_tmp350)
	_tmp352 = ol_total + _tmp351
	ol_total = _tmp352
	_tmp353 = ol_number + 1
	ol_number = _tmp353
	goto BB113
BB116:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp354 = row6.C_BALANCE
	_tmp355 = _tmp354 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp355
	_tmp356 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id}, row7)
	_tmp357 = _tmp356 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp357
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop7 lowers hop 7 containing 4 basic block(s).
func DeliveryHop7(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp358 uint64
	var _tmp359 uint64
	var c_id uint64
	var _tmp360 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp362 bool
	var _tmp363 uint64
	var _tmp364 float32
	var _tmp365 float32
	var _tmp366 uint64
	var _tmp367 float32
	var _tmp368 float32
	var _tmp369 float32
	var _tmp370 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB117

BB117:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 7})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp358 = row1.D_NEXT_NO_ID
	no_o_id = _tmp358
	_tmp359 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 7})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp359
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 7}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 7, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp360 = row3.O_C_ID
	c_id = _tmp360
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 7, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 7, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB118
BB118:
	_tmp362 = ol_number < O_OL_CNT
	if _tmp362 {
		goto BB119
	} else {
		goto BB121
	}
BB119:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 7, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp363 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 7, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp364 = float32(_tmp363)
	_tmp365 = ol_total + _tmp364
	ol_total = _tmp365
	_tmp366 = ol_number + 1
	ol_number = _tmp366
	goto BB118
BB121:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp367 = row6.C_BALANCE
	_tmp368 = _tmp367 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp368
	_tmp369 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id}, row7)
	_tmp370 = _tmp369 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp370
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop8 lowers hop 8 containing 4 basic block(s).
func DeliveryHop8(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp371 uint64
	var _tmp372 uint64
	var c_id uint64
	var _tmp373 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp375 bool
	var _tmp376 uint64
	var _tmp377 float32
	var _tmp378 float32
	var _tmp379 uint64
	var _tmp380 float32
	var _tmp381 float32
	var _tmp382 float32
	var _tmp383 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB122

BB122:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 8})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp371 = row1.D_NEXT_NO_ID
	no_o_id = _tmp371
	_tmp372 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 8})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp372
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 8}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 8, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp373 = row3.O_C_ID
	c_id = _tmp373
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 8, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 8, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB123
BB123:
	_tmp375 = ol_number < O_OL_CNT
	if _tmp375 {
		goto BB124
	} else {
		goto BB126
	}
BB124:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 8, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp376 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 8, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp377 = float32(_tmp376)
	_tmp378 = ol_total + _tmp377
	ol_total = _tmp378
	_tmp379 = ol_number + 1
	ol_number = _tmp379
	goto BB123
BB126:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp380 = row6.C_BALANCE
	_tmp381 = _tmp380 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp381
	_tmp382 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id}, row7)
	_tmp383 = _tmp382 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp383
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop9 lowers hop 9 containing 4 basic block(s).
func DeliveryHop9(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp384 uint64
	var _tmp385 uint64
	var c_id uint64
	var _tmp386 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp388 bool
	var _tmp389 uint64
	var _tmp390 float32
	var _tmp391 float32
	var _tmp392 uint64
	var _tmp393 float32
	var _tmp394 float32
	var _tmp395 float32
	var _tmp396 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	goto BB127

BB127:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 9})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp384 = row1.D_NEXT_NO_ID
	no_o_id = _tmp384
	_tmp385 = no_o_id + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 9})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp385
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 9}, row2)
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 9, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp386 = row3.O_C_ID
	c_id = _tmp386
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 9, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 9, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB128
BB128:
	_tmp388 = ol_number < O_OL_CNT
	if _tmp388 {
		goto BB129
	} else {
		goto BB131
	}
BB129:
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 9, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp389 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 9, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp390 = float32(_tmp389)
	_tmp391 = ol_total + _tmp390
	ol_total = _tmp391
	_tmp392 = ol_number + 1
	ol_number = _tmp392
	goto BB128
BB131:
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp393 = row6.C_BALANCE
	_tmp394 = _tmp393 + ol_total
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp394
	_tmp395 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id}, row7)
	_tmp396 = _tmp395 + 1
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp396
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id}, row8)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// DeliveryHop0Par calculates the partition for hop 0 without database access.
func DeliveryHop0Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp267 uint64
	var _tmp268 uint64
	var c_id uint64
	var _tmp269 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp271 bool
	var _tmp272 uint64
	var _tmp273 float32
	var _tmp274 float32
	var _tmp275 uint64
	var _tmp276 float32
	var _tmp277 float32
	var _tmp278 float32
	var _tmp279 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB82

BB82:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 0}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 0})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp267 = row1.D_NEXT_NO_ID
	no_o_id = _tmp267
	_tmp268 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 0}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 0})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp268
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 0}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 0, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 0, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp269 = row3.O_C_ID
	c_id = _tmp269
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 0, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 0, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 0, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB83
BB83:
	_tmp271 = ol_number < O_OL_CNT
	if _tmp271 {
		goto BB84
	} else {
		goto BB86
	}
BB84:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 0, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 0, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp272 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 0, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp273 = float32(_tmp272)
	_tmp274 = ol_total + _tmp273
	ol_total = _tmp274
	_tmp275 = ol_number + 1
	ol_number = _tmp275
	goto BB83
BB86:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp276 = row6.C_BALANCE
	_tmp277 = _tmp276 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp277
	_tmp278 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id}, row7)
	_tmp279 = _tmp278 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp279
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 0, C_ID: c_id}, row8)
	panic("unexpected hop exit in partition")
}

// DeliveryHop1Par calculates the partition for hop 1 without database access.
func DeliveryHop1Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp280 uint64
	var _tmp281 uint64
	var c_id uint64
	var _tmp282 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp284 bool
	var _tmp285 uint64
	var _tmp286 float32
	var _tmp287 float32
	var _tmp288 uint64
	var _tmp289 float32
	var _tmp290 float32
	var _tmp291 float32
	var _tmp292 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB87

BB87:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 1}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 1})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp280 = row1.D_NEXT_NO_ID
	no_o_id = _tmp280
	_tmp281 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 1}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 1})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp281
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 1}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 1, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 1, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp282 = row3.O_C_ID
	c_id = _tmp282
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 1, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 1, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 1, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB88
BB88:
	_tmp284 = ol_number < O_OL_CNT
	if _tmp284 {
		goto BB89
	} else {
		goto BB91
	}
BB89:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 1, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 1, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp285 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 1, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp286 = float32(_tmp285)
	_tmp287 = ol_total + _tmp286
	ol_total = _tmp287
	_tmp288 = ol_number + 1
	ol_number = _tmp288
	goto BB88
BB91:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp289 = row6.C_BALANCE
	_tmp290 = _tmp289 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp290
	_tmp291 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id}, row7)
	_tmp292 = _tmp291 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp292
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 1, C_ID: c_id}, row8)
	panic("unexpected hop exit in partition")
}

// DeliveryHop2Par calculates the partition for hop 2 without database access.
func DeliveryHop2Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp293 uint64
	var _tmp294 uint64
	var c_id uint64
	var _tmp295 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp297 bool
	var _tmp298 uint64
	var _tmp299 float32
	var _tmp300 float32
	var _tmp301 uint64
	var _tmp302 float32
	var _tmp303 float32
	var _tmp304 float32
	var _tmp305 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB92

BB92:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 2}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 2})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp293 = row1.D_NEXT_NO_ID
	no_o_id = _tmp293
	_tmp294 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 2}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 2})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp294
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 2}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 2, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 2, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp295 = row3.O_C_ID
	c_id = _tmp295
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 2, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 2, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 2, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB93
BB93:
	_tmp297 = ol_number < O_OL_CNT
	if _tmp297 {
		goto BB94
	} else {
		goto BB96
	}
BB94:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 2, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 2, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp298 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 2, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp299 = float32(_tmp298)
	_tmp300 = ol_total + _tmp299
	ol_total = _tmp300
	_tmp301 = ol_number + 1
	ol_number = _tmp301
	goto BB93
BB96:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp302 = row6.C_BALANCE
	_tmp303 = _tmp302 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp303
	_tmp304 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id}, row7)
	_tmp305 = _tmp304 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp305
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 2, C_ID: c_id}, row8)
	panic("unexpected hop exit in partition")
}

// DeliveryHop3Par calculates the partition for hop 3 without database access.
func DeliveryHop3Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp306 uint64
	var _tmp307 uint64
	var c_id uint64
	var _tmp308 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp310 bool
	var _tmp311 uint64
	var _tmp312 float32
	var _tmp313 float32
	var _tmp314 uint64
	var _tmp315 float32
	var _tmp316 float32
	var _tmp317 float32
	var _tmp318 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB97

BB97:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 3}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 3})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp306 = row1.D_NEXT_NO_ID
	no_o_id = _tmp306
	_tmp307 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 3}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 3})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp307
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 3}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 3, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 3, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp308 = row3.O_C_ID
	c_id = _tmp308
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 3, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 3, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 3, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB98
BB98:
	_tmp310 = ol_number < O_OL_CNT
	if _tmp310 {
		goto BB99
	} else {
		goto BB101
	}
BB99:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 3, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 3, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp311 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 3, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp312 = float32(_tmp311)
	_tmp313 = ol_total + _tmp312
	ol_total = _tmp313
	_tmp314 = ol_number + 1
	ol_number = _tmp314
	goto BB98
BB101:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp315 = row6.C_BALANCE
	_tmp316 = _tmp315 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp316
	_tmp317 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id}, row7)
	_tmp318 = _tmp317 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp318
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 3, C_ID: c_id}, row8)
	panic("unexpected hop exit in partition")
}

// DeliveryHop4Par calculates the partition for hop 4 without database access.
func DeliveryHop4Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp319 uint64
	var _tmp320 uint64
	var c_id uint64
	var _tmp321 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp323 bool
	var _tmp324 uint64
	var _tmp325 float32
	var _tmp326 float32
	var _tmp327 uint64
	var _tmp328 float32
	var _tmp329 float32
	var _tmp330 float32
	var _tmp331 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB102

BB102:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 4}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 4})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp319 = row1.D_NEXT_NO_ID
	no_o_id = _tmp319
	_tmp320 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 4}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 4})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp320
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 4}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 4, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 4, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp321 = row3.O_C_ID
	c_id = _tmp321
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 4, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 4, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 4, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB103
BB103:
	_tmp323 = ol_number < O_OL_CNT
	if _tmp323 {
		goto BB104
	} else {
		goto BB106
	}
BB104:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 4, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 4, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp324 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 4, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp325 = float32(_tmp324)
	_tmp326 = ol_total + _tmp325
	ol_total = _tmp326
	_tmp327 = ol_number + 1
	ol_number = _tmp327
	goto BB103
BB106:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp328 = row6.C_BALANCE
	_tmp329 = _tmp328 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp329
	_tmp330 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id}, row7)
	_tmp331 = _tmp330 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp331
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 4, C_ID: c_id}, row8)
	panic("unexpected hop exit in partition")
}

// DeliveryHop5Par calculates the partition for hop 5 without database access.
func DeliveryHop5Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp332 uint64
	var _tmp333 uint64
	var c_id uint64
	var _tmp334 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp336 bool
	var _tmp337 uint64
	var _tmp338 float32
	var _tmp339 float32
	var _tmp340 uint64
	var _tmp341 float32
	var _tmp342 float32
	var _tmp343 float32
	var _tmp344 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB107

BB107:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 5}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 5})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp332 = row1.D_NEXT_NO_ID
	no_o_id = _tmp332
	_tmp333 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 5}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 5})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp333
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 5}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 5, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 5, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp334 = row3.O_C_ID
	c_id = _tmp334
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 5, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 5, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 5, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB108
BB108:
	_tmp336 = ol_number < O_OL_CNT
	if _tmp336 {
		goto BB109
	} else {
		goto BB111
	}
BB109:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 5, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 5, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp337 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 5, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp338 = float32(_tmp337)
	_tmp339 = ol_total + _tmp338
	ol_total = _tmp339
	_tmp340 = ol_number + 1
	ol_number = _tmp340
	goto BB108
BB111:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp341 = row6.C_BALANCE
	_tmp342 = _tmp341 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp342
	_tmp343 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id}, row7)
	_tmp344 = _tmp343 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp344
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 5, C_ID: c_id}, row8)
	panic("unexpected hop exit in partition")
}

// DeliveryHop6Par calculates the partition for hop 6 without database access.
func DeliveryHop6Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp345 uint64
	var _tmp346 uint64
	var c_id uint64
	var _tmp347 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp349 bool
	var _tmp350 uint64
	var _tmp351 float32
	var _tmp352 float32
	var _tmp353 uint64
	var _tmp354 float32
	var _tmp355 float32
	var _tmp356 float32
	var _tmp357 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB112

BB112:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 6}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 6})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp345 = row1.D_NEXT_NO_ID
	no_o_id = _tmp345
	_tmp346 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 6}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 6})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp346
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 6}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 6, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 6, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp347 = row3.O_C_ID
	c_id = _tmp347
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 6, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 6, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 6, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB113
BB113:
	_tmp349 = ol_number < O_OL_CNT
	if _tmp349 {
		goto BB114
	} else {
		goto BB116
	}
BB114:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 6, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 6, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp350 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 6, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp351 = float32(_tmp350)
	_tmp352 = ol_total + _tmp351
	ol_total = _tmp352
	_tmp353 = ol_number + 1
	ol_number = _tmp353
	goto BB113
BB116:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp354 = row6.C_BALANCE
	_tmp355 = _tmp354 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp355
	_tmp356 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id}, row7)
	_tmp357 = _tmp356 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp357
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 6, C_ID: c_id}, row8)
	panic("unexpected hop exit in partition")
}

// DeliveryHop7Par calculates the partition for hop 7 without database access.
func DeliveryHop7Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp358 uint64
	var _tmp359 uint64
	var c_id uint64
	var _tmp360 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp362 bool
	var _tmp363 uint64
	var _tmp364 float32
	var _tmp365 float32
	var _tmp366 uint64
	var _tmp367 float32
	var _tmp368 float32
	var _tmp369 float32
	var _tmp370 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB117

BB117:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 7}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 7})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp358 = row1.D_NEXT_NO_ID
	no_o_id = _tmp358
	_tmp359 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 7}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 7})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp359
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 7}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 7, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 7, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp360 = row3.O_C_ID
	c_id = _tmp360
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 7, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 7, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 7, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB118
BB118:
	_tmp362 = ol_number < O_OL_CNT
	if _tmp362 {
		goto BB119
	} else {
		goto BB121
	}
BB119:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 7, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 7, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp363 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 7, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp364 = float32(_tmp363)
	_tmp365 = ol_total + _tmp364
	ol_total = _tmp365
	_tmp366 = ol_number + 1
	ol_number = _tmp366
	goto BB118
BB121:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp367 = row6.C_BALANCE
	_tmp368 = _tmp367 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp368
	_tmp369 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id}, row7)
	_tmp370 = _tmp369 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp370
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 7, C_ID: c_id}, row8)
	panic("unexpected hop exit in partition")
}

// DeliveryHop8Par calculates the partition for hop 8 without database access.
func DeliveryHop8Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp371 uint64
	var _tmp372 uint64
	var c_id uint64
	var _tmp373 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp375 bool
	var _tmp376 uint64
	var _tmp377 float32
	var _tmp378 float32
	var _tmp379 uint64
	var _tmp380 float32
	var _tmp381 float32
	var _tmp382 float32
	var _tmp383 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB122

BB122:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 8}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 8})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp371 = row1.D_NEXT_NO_ID
	no_o_id = _tmp371
	_tmp372 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 8}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 8})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp372
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 8}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 8, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 8, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp373 = row3.O_C_ID
	c_id = _tmp373
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 8, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 8, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 8, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB123
BB123:
	_tmp375 = ol_number < O_OL_CNT
	if _tmp375 {
		goto BB124
	} else {
		goto BB126
	}
BB124:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 8, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 8, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp376 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 8, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp377 = float32(_tmp376)
	_tmp378 = ol_total + _tmp377
	ol_total = _tmp378
	_tmp379 = ol_number + 1
	ol_number = _tmp379
	goto BB123
BB126:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp380 = row6.C_BALANCE
	_tmp381 = _tmp380 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp381
	_tmp382 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id}, row7)
	_tmp383 = _tmp382 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp383
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 8, C_ID: c_id}, row8)
	panic("unexpected hop exit in partition")
}

// DeliveryHop9Par calculates the partition for hop 9 without database access.
func DeliveryHop9Par(params map[string]string) uint64 {
	var w_id uint64
	var o_carrier_id uint64
	var date uint64
	var no_o_id uint64
	var _tmp384 uint64
	var _tmp385 uint64
	var c_id uint64
	var _tmp386 uint64
	var ol_total float32
	var ol_number uint64
	var _tmp388 bool
	var _tmp389 uint64
	var _tmp390 float32
	var _tmp391 float32
	var _tmp392 uint64
	var _tmp393 float32
	var _tmp394 float32
	var _tmp395 float32
	var _tmp396 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 Order
	var keyBytes5 []byte
	var row5 OrderLine
	var keyBytes6 []byte
	var row6 Customer
	var keyBytes7 []byte
	var row7 Customer
	var keyBytes8 []byte
	var row8 Customer

	w_id = toUint64(params["w_id"])
	o_carrier_id = toUint64(params["o_carrier_id"])
	date = toUint64(params["date"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB127

BB127:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 9}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 9})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp384 = row1.D_NEXT_NO_ID
	no_o_id = _tmp384
	_tmp385 = no_o_id + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: 9}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 9})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_NO_ID = _tmp385
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: 9}, row2)
	// First table access - calculate partition: Order
	if true { return getOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 9, O_ID: no_o_id}) }
	// TableGet: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 9, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	_tmp386 = row3.O_C_ID
	c_id = _tmp386
	// First table access - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: 9, O_ID: no_o_id}) }
	// TableSet: Order
	keyBytes4, row4 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 9, O_ID: no_o_id})
	rwSet = AddRWSet(rwSet, "Order", keyBytes4)
	row4.O_CARRIER_ID = o_carrier_id
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: 9, O_ID: no_o_id}, row4)
	ol_total = 0
	ol_number = 0
	goto BB128
BB128:
	_tmp388 = ol_number < O_OL_CNT
	if _tmp388 {
		goto BB129
	} else {
		goto BB131
	}
BB129:
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: 9, OL_O_ID: no_o_id, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 9, OL_O_ID: no_o_id, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_DELIVERY_DATE = date
	_tmp389 = row5.OL_AMOUNT
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: 9, OL_O_ID: no_o_id, OL_NUMBER: ol_number}, row5)
	_tmp390 = float32(_tmp389)
	_tmp391 = ol_total + _tmp390
	ol_total = _tmp391
	_tmp392 = ol_number + 1
	ol_number = _tmp392
	goto BB128
BB131:
	// First table access - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id}) }
	// TableGet: Customer
	keyBytes6, row6 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes6)
	_tmp393 = row6.C_BALANCE
	_tmp394 = _tmp393 + ol_total
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes7, row7 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes7)
	row7.C_BALANCE = _tmp394
	_tmp395 = row7.C_DELIVERY_CNT
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id}, row7)
	_tmp396 = _tmp395 + 1
	// First table access - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id}) }
	// TableSet: Customer
	keyBytes8, row8 = getCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes8)
	row8.C_DELIVERY_CNT = _tmp396
	putCustomer(tx, CustomerKey{C_W_ID: w_id, C_D_ID: 9, C_ID: c_id}, row8)
	return 0
}

func DeliveryNextReq(in *proto.TrxRes, params map[string]string, shards int) (*proto.TrxReq, map[string]string, int) {
	hopId := in.Info.Hopid
	req := &proto.TrxReq{Info: in.Info}
	nextShard := 0

	switch hopId {
	case 0:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop0Par(paramsCopy))
	case 1:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop1Par(paramsCopy))
	case 2:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop2Par(paramsCopy))
	case 3:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop3Par(paramsCopy))
	case 4:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop4Par(paramsCopy))
	case 5:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop5Par(paramsCopy))
	case 6:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop6Par(paramsCopy))
	case 7:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop7Par(paramsCopy))
	case 8:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop8Par(paramsCopy))
	case 9:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(DeliveryHop9Par(paramsCopy))
	default:
		return nil, params, 0
	}

	req.Params = params
	req.Info.Hopid += 1
	req.Dependency = in.Dependency
	return req, params, nextShard
}

func DeliveryChainImpl(db *bolt.DB) *Chain {
	// Create the list of hops
	hops := make([]*Hop, 10)

	hops[0] = &Hop{
		id:         0,
		hopType:    util.MergedHopBegin,
		isReadOnly: false,
		process:    DeliveryHop0,
		conflicts:  map[int32]int32{0: 11, 1: 0},
	}

	hops[1] = &Hop{
		id:         1,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    DeliveryHop1,
		conflicts:  map[int32]int32{0: 11, 1: 1},
	}

	hops[2] = &Hop{
		id:         2,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    DeliveryHop2,
		conflicts:  map[int32]int32{0: 11, 1: 2},
	}

	hops[3] = &Hop{
		id:         3,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    DeliveryHop3,
		conflicts:  map[int32]int32{0: 11, 1: 3},
	}

	hops[4] = &Hop{
		id:         4,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    DeliveryHop4,
		conflicts:  map[int32]int32{0: 11, 1: 4},
	}

	hops[5] = &Hop{
		id:         5,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    DeliveryHop5,
		conflicts:  map[int32]int32{0: 11, 1: 5},
	}

	hops[6] = &Hop{
		id:         6,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    DeliveryHop6,
		conflicts:  map[int32]int32{0: 11, 1: 6},
	}

	hops[7] = &Hop{
		id:         7,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    DeliveryHop7,
		conflicts:  map[int32]int32{0: 11, 1: 7},
	}

	hops[8] = &Hop{
		id:         8,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    DeliveryHop8,
		conflicts:  map[int32]int32{0: 11, 1: 8},
	}

	hops[9] = &Hop{
		id:         9,
		hopType:    util.MergedHopEnd,
		isReadOnly: false,
		process:    DeliveryHop9,
		conflicts:  map[int32]int32{0: 11, 1: 9},
	}

	// add field names
	return &Chain{db: db, hops: hops, NextReq: DeliveryNextReq}
}

func DeliveryToJSON(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

