// Code generated by FMitF Go code generator. DO NOT EDIT.

package chainManager

import (
	"encoding/json"
	"github.com/boltdb/bolt"
)

func mustJSON(value any) []byte {
	bytes, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return bytes
}

const (
	__slice__ uint64 = 0
	O_OL_CNT uint64 = 10
)

type WarehouseKey struct {
	W_ID uint64
}

type Warehouse struct {
	Key WarehouseKey
	W_NAME string
	W_STREET_1 string
	W_STREET_2 string
	W_CITY string
	W_STATE string
	W_ZIP string
	W_TAX float32
	W_YTD float32
}

func getWarehouse(tx *bolt.Tx, key WarehouseKey) ([]byte, Warehouse) {
	bucket := tx.Bucket([]byte("tWarehouse"))
	if bucket == nil {
		panic("missing bucket tWarehouse")
	}
	keyBytes := mustJSON(key)
	var row Warehouse
	if data := bucket.Get(keyBytes); data != nil {
		if err := json.Unmarshal(data, &row); err != nil {
			panic(err)
		}
	}
	row.Key = key
	return keyBytes, row
}

func putWarehouse(tx *bolt.Tx, key WarehouseKey, row Warehouse) {
	bucket := tx.Bucket([]byte("tWarehouse"))
	if bucket == nil {
		panic("missing bucket tWarehouse")
	}
	row.Key = key
	putData(bucket, mustJSON(key), mustJSON(row))
}

func getWarehousePar(key WarehouseKey) uint64 {
	// Call partition function to determine shard
	return f(key.W_ID)
}

func putWarehousePar(key WarehouseKey) uint64 {
	// Call partition function to determine shard
	return f(key.W_ID)
}

type DistrictKey struct {
	D_W_ID uint64
	D_ID uint64
}

type District struct {
	Key DistrictKey
	D_NAME string
	D_STREET_1 string
	D_STREET_2 string
	D_CITY string
	D_STATE string
	D_ZIP string
	D_TAX float32
	D_YTD float32
	D_NEXT_O_ID uint64
	D_NEXT_NO_ID uint64
}

func getDistrict(tx *bolt.Tx, key DistrictKey) ([]byte, District) {
	bucket := tx.Bucket([]byte("tDistrict"))
	if bucket == nil {
		panic("missing bucket tDistrict")
	}
	keyBytes := mustJSON(key)
	var row District
	if data := bucket.Get(keyBytes); data != nil {
		if err := json.Unmarshal(data, &row); err != nil {
			panic(err)
		}
	}
	row.Key = key
	return keyBytes, row
}

func putDistrict(tx *bolt.Tx, key DistrictKey, row District) {
	bucket := tx.Bucket([]byte("tDistrict"))
	if bucket == nil {
		panic("missing bucket tDistrict")
	}
	row.Key = key
	putData(bucket, mustJSON(key), mustJSON(row))
}

func getDistrictPar(key DistrictKey) uint64 {
	// Call partition function to determine shard
	return g(key.D_W_ID, key.D_ID)
}

func putDistrictPar(key DistrictKey) uint64 {
	// Call partition function to determine shard
	return g(key.D_W_ID, key.D_ID)
}

type CustomerKey struct {
	C_W_ID uint64
	C_D_ID uint64
	C_ID uint64
}

type Customer struct {
	Key CustomerKey
	C_FIRST string
	C_MIDDLE string
	C_LAST string
	C_STREET_1 string
	C_STREET_2 string
	C_CITY string
	C_STATE string
	C_ZIP string
	C_PHONE string
	C_SINCE uint64
	C_CREDIT string
	C_CREDIT_LIMIT float32
	C_DISCOUNT float32
	C_BALANCE float32
	C_YTD_PAYMENT float32
	C_PAYMENT_CNT float32
	C_DELIVERY_CNT float32
	C_DATA string
}

func getCustomer(tx *bolt.Tx, key CustomerKey) ([]byte, Customer) {
	bucket := tx.Bucket([]byte("tCustomer"))
	if bucket == nil {
		panic("missing bucket tCustomer")
	}
	keyBytes := mustJSON(key)
	var row Customer
	if data := bucket.Get(keyBytes); data != nil {
		if err := json.Unmarshal(data, &row); err != nil {
			panic(err)
		}
	}
	row.Key = key
	return keyBytes, row
}

func putCustomer(tx *bolt.Tx, key CustomerKey, row Customer) {
	bucket := tx.Bucket([]byte("tCustomer"))
	if bucket == nil {
		panic("missing bucket tCustomer")
	}
	row.Key = key
	putData(bucket, mustJSON(key), mustJSON(row))
}

func getCustomerPar(key CustomerKey) uint64 {
	// Call partition function to determine shard
	return g(key.C_W_ID, key.C_D_ID)
}

func putCustomerPar(key CustomerKey) uint64 {
	// Call partition function to determine shard
	return g(key.C_W_ID, key.C_D_ID)
}

type NewOrderKey struct {
	NO_W_ID uint64
	NO_D_ID uint64
	NO_O_ID uint64
}

type NewOrder struct {
	Key NewOrderKey
}

func getNewOrder(tx *bolt.Tx, key NewOrderKey) ([]byte, NewOrder) {
	bucket := tx.Bucket([]byte("tNewOrder"))
	if bucket == nil {
		panic("missing bucket tNewOrder")
	}
	keyBytes := mustJSON(key)
	var row NewOrder
	if data := bucket.Get(keyBytes); data != nil {
		if err := json.Unmarshal(data, &row); err != nil {
			panic(err)
		}
	}
	row.Key = key
	return keyBytes, row
}

func putNewOrder(tx *bolt.Tx, key NewOrderKey, row NewOrder) {
	bucket := tx.Bucket([]byte("tNewOrder"))
	if bucket == nil {
		panic("missing bucket tNewOrder")
	}
	row.Key = key
	putData(bucket, mustJSON(key), mustJSON(row))
}

func getNewOrderPar(key NewOrderKey) uint64 {
	// Call partition function to determine shard
	return g(key.NO_W_ID, key.NO_D_ID)
}

func putNewOrderPar(key NewOrderKey) uint64 {
	// Call partition function to determine shard
	return g(key.NO_W_ID, key.NO_D_ID)
}

type OrderKey struct {
	O_W_ID uint64
	O_D_ID uint64
	O_ID uint64
}

type Order struct {
	Key OrderKey
	O_C_ID uint64
	O_ENTRY_DATE uint64
	O_CARRIER_ID uint64
	O_OL_CNT uint64
	O_ALL_LOCAL uint64
}

func getOrder(tx *bolt.Tx, key OrderKey) ([]byte, Order) {
	bucket := tx.Bucket([]byte("tOrder"))
	if bucket == nil {
		panic("missing bucket tOrder")
	}
	keyBytes := mustJSON(key)
	var row Order
	if data := bucket.Get(keyBytes); data != nil {
		if err := json.Unmarshal(data, &row); err != nil {
			panic(err)
		}
	}
	row.Key = key
	return keyBytes, row
}

func putOrder(tx *bolt.Tx, key OrderKey, row Order) {
	bucket := tx.Bucket([]byte("tOrder"))
	if bucket == nil {
		panic("missing bucket tOrder")
	}
	row.Key = key
	putData(bucket, mustJSON(key), mustJSON(row))
}

func getOrderPar(key OrderKey) uint64 {
	// Call partition function to determine shard
	return g(key.O_W_ID, key.O_D_ID)
}

func putOrderPar(key OrderKey) uint64 {
	// Call partition function to determine shard
	return g(key.O_W_ID, key.O_D_ID)
}

type OrderLineKey struct {
	OL_W_ID uint64
	OL_D_ID uint64
	OL_O_ID uint64
	OL_NUMBER uint64
}

type OrderLine struct {
	Key OrderLineKey
	OL_I_ID uint64
	OL_SUPPLY_W_ID uint64
	OL_DELIVERY_DATE uint64
	OL_QUANTITY uint64
	OL_AMOUNT uint64
	OL_DIST_INTO string
}

func getOrderLine(tx *bolt.Tx, key OrderLineKey) ([]byte, OrderLine) {
	bucket := tx.Bucket([]byte("tOrderLine"))
	if bucket == nil {
		panic("missing bucket tOrderLine")
	}
	keyBytes := mustJSON(key)
	var row OrderLine
	if data := bucket.Get(keyBytes); data != nil {
		if err := json.Unmarshal(data, &row); err != nil {
			panic(err)
		}
	}
	row.Key = key
	return keyBytes, row
}

func putOrderLine(tx *bolt.Tx, key OrderLineKey, row OrderLine) {
	bucket := tx.Bucket([]byte("tOrderLine"))
	if bucket == nil {
		panic("missing bucket tOrderLine")
	}
	row.Key = key
	putData(bucket, mustJSON(key), mustJSON(row))
}

func getOrderLinePar(key OrderLineKey) uint64 {
	// Call partition function to determine shard
	return g(key.OL_W_ID, key.OL_D_ID)
}

func putOrderLinePar(key OrderLineKey) uint64 {
	// Call partition function to determine shard
	return g(key.OL_W_ID, key.OL_D_ID)
}

type ItemKey struct {
	I_ID uint64
	W_ID uint64
}

type Item struct {
	Key ItemKey
	I_IM_ID uint64
	I_NAME string
	I_PRICE float32
	I_DATA string
}

func getItem(tx *bolt.Tx, key ItemKey) ([]byte, Item) {
	bucket := tx.Bucket([]byte("tItem"))
	if bucket == nil {
		panic("missing bucket tItem")
	}
	keyBytes := mustJSON(key)
	var row Item
	if data := bucket.Get(keyBytes); data != nil {
		if err := json.Unmarshal(data, &row); err != nil {
			panic(err)
		}
	}
	row.Key = key
	return keyBytes, row
}

func putItem(tx *bolt.Tx, key ItemKey, row Item) {
	bucket := tx.Bucket([]byte("tItem"))
	if bucket == nil {
		panic("missing bucket tItem")
	}
	row.Key = key
	putData(bucket, mustJSON(key), mustJSON(row))
}

func getItemPar(key ItemKey) uint64 {
	// Call partition function to determine shard
	return h(key.W_ID, key.I_ID)
}

func putItemPar(key ItemKey) uint64 {
	// Call partition function to determine shard
	return h(key.W_ID, key.I_ID)
}

type StockKey struct {
	S_W_ID uint64
	S_I_ID uint64
}

type Stock struct {
	Key StockKey
	S_QUANTITY uint64
	S_YTD float32
	S_ORDER_CNT uint64
	S_REMOTE_CNT uint64
	S_DATA string
}

func getStock(tx *bolt.Tx, key StockKey) ([]byte, Stock) {
	bucket := tx.Bucket([]byte("tStock"))
	if bucket == nil {
		panic("missing bucket tStock")
	}
	keyBytes := mustJSON(key)
	var row Stock
	if data := bucket.Get(keyBytes); data != nil {
		if err := json.Unmarshal(data, &row); err != nil {
			panic(err)
		}
	}
	row.Key = key
	return keyBytes, row
}

func putStock(tx *bolt.Tx, key StockKey, row Stock) {
	bucket := tx.Bucket([]byte("tStock"))
	if bucket == nil {
		panic("missing bucket tStock")
	}
	row.Key = key
	putData(bucket, mustJSON(key), mustJSON(row))
}

func getStockPar(key StockKey) uint64 {
	// Call partition function to determine shard
	return h(key.S_W_ID, key.S_I_ID)
}

func putStockPar(key StockKey) uint64 {
	// Call partition function to determine shard
	return h(key.S_W_ID, key.S_I_ID)
}

func f(x uint64) uint64 {
	var _tmp56 uint64
	goto BB13

BB13:
	_tmp56 = 10 * x
	return _tmp56
}

func g(x uint64, y uint64) uint64 {
	var _tmp58 uint64
	var _tmp57 uint64
	goto BB14

BB14:
	_tmp57 = 10 * x
	_tmp58 = _tmp57 + y
	return _tmp58
}

func h(x uint64, y uint64) uint64 {
	var _tmp60 uint64
	var _tmp61 uint64
	var _tmp59 uint64
	goto BB15

BB15:
	_tmp59 = 10 * x
	_tmp60 = y % 10
	_tmp61 = _tmp59 + _tmp60
	return _tmp61
}

func Scheds() {
	// Initialize scheduler maps
	LockSchedulers = make(map[string]*Scheduler)
	AccessSchedulers = make(map[string]*Scheduler)
	AccessDSchedulers = make(map[string]*Scheduler)

	// Create one lock scheduler for each table
	LockSchedulers["Warehouse"] = NewScheduler()
	LockSchedulers["District"] = NewScheduler()
	LockSchedulers["Customer"] = NewScheduler()
	LockSchedulers["NewOrder"] = NewScheduler()
	LockSchedulers["Order"] = NewScheduler()
	LockSchedulers["OrderLine"] = NewScheduler()
	LockSchedulers["Item"] = NewScheduler()
	LockSchedulers["Stock"] = NewScheduler()

	// Create one access scheduler for each table in hops that has C-edges
	AccessSchedulers["District"] = NewScheduler()
	AccessSchedulers["Customer"] = NewScheduler()
	AccessSchedulers["Order"] = NewScheduler()
	AccessSchedulers["OrderLine"] = NewScheduler()
}

func Chains(db *bolt.DB) []*Chain {
	return []*Chain{
		NeworderChainImpl(db),
		DeliveryChainImpl(db),
		PaymentChainImpl(db),
	}
}

func ChainsP(db *bolt.DB) []*Chain {
	return []*Chain{
		NeworderChainPreOptImpl(db),
		DeliveryChainImpl(db),
		PaymentChainImpl(db),
	}
}

