// Code generated by FMitF Go code generator. DO NOT EDIT.

package chainManager

import (
	"encoding/json"
	"github.com/boltdb/bolt"
	"ShardDB/proto"
	"ShardDB/util"
)

type NeworderChain struct {
	db   *bolt.DB
	hops []*Hop
}

// NeworderHop0 lowers hop 0 containing 1 basic block(s).
func NeworderHop0(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var w_tax float32
	var _tmp62 float32
	var prices []float32
	var _tmp63 []float32

	var keyBytes1 []byte
	var row1 Warehouse

	w_id = toUint64(params["w_id"])

	goto BB16

BB16:
	// TableGet: Warehouse
	keyBytes1, row1 = getWarehouse(tx, WarehouseKey{W_ID: w_id})
	rwSet = AddRWSet(rwSet, "Warehouse", keyBytes1)
	_tmp62 = row1.W_TAX
	w_tax = _tmp62
	_tmp63 = nil
	prices = _tmp63
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{fromFloat32(w_tax), string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop1 lowers hop 1 containing 6 basic block(s).
func NeworderHop1(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var i_id uint64
	var _tmp64 uint64
	var sup_w_id uint64
	var _tmp65 uint64
	var qty uint64
	var _tmp66 uint64
	var _tmp67 bool
	var _tmp68 bool
	var _tmp69 bool
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var price float32
	var _tmp71 float32
	var _tmp72 []float32
	var _tmp73 uint64
	var _tmp74 bool
	var _tmp75 uint64
	var _tmp76 uint64
	var _tmp77 uint64
	var _tmp78 bool
	var _tmp79 uint64
	var _tmp80 uint64
	var _tmp81 float32
	var _tmp82 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB17

BB17:
	_tmp64 = listGet(itemIDs, int(0))
	i_id = _tmp64
	_tmp65 = listGet(supplierWarehouseIDs, int(0))
	sup_w_id = _tmp65
	_tmp66 = listGet(orderQuantities, int(0))
	qty = _tmp66
	_tmp67 = qty >= 0
	_tmp68 = qty <= 10
	_tmp69 = _tmp67 && _tmp68
	if !(_tmp69) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp71 = row2.I_PRICE
	price = _tmp71
	_tmp72 = append(prices, price)
	prices = _tmp72
	_tmp73 = s_S_QUANTITY - qty
	_tmp74 = _tmp73 >= 10
	if _tmp74 {
		goto BB18
	} else {
		goto BB20
	}
BB18:
	_tmp75 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp75
	goto BB19
BB19:
	_tmp78 = sup_w_id != w_id
	if _tmp78 {
		goto BB21
	} else {
		goto BB22
	}
BB20:
	_tmp76 = s_S_QUANTITY + 91
	_tmp77 = _tmp76 - qty
	s_S_QUANTITY = _tmp77
	goto BB19
BB21:
	_tmp79 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp79
	goto BB22
BB22:
	_tmp80 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp80
	_tmp81 = float32(qty)
	_tmp82 = s_S_YTD + _tmp81
	s_S_YTD = _tmp82
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop2 lowers hop 2 containing 6 basic block(s).
func NeworderHop2(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp83 uint64
	var sup_w_id uint64
	var _tmp84 uint64
	var qty uint64
	var _tmp85 uint64
	var _tmp86 bool
	var _tmp87 bool
	var _tmp88 bool
	var price float32
	var _tmp90 float32
	var _tmp91 []float32
	var _tmp92 uint64
	var _tmp93 bool
	var _tmp94 uint64
	var _tmp95 uint64
	var _tmp96 uint64
	var _tmp97 bool
	var _tmp98 uint64
	var _tmp99 uint64
	var _tmp100 float32
	var _tmp101 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB23

BB23:
	_tmp83 = listGet(itemIDs, int(1))
	i_id = _tmp83
	_tmp84 = listGet(supplierWarehouseIDs, int(1))
	sup_w_id = _tmp84
	_tmp85 = listGet(orderQuantities, int(1))
	qty = _tmp85
	_tmp86 = qty >= 0
	_tmp87 = qty <= 10
	_tmp88 = _tmp86 && _tmp87
	if !(_tmp88) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp90 = row2.I_PRICE
	price = _tmp90
	_tmp91 = append(prices, price)
	prices = _tmp91
	_tmp92 = s_S_QUANTITY - qty
	_tmp93 = _tmp92 >= 10
	if _tmp93 {
		goto BB24
	} else {
		goto BB26
	}
BB24:
	_tmp94 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp94
	goto BB25
BB25:
	_tmp97 = sup_w_id != w_id
	if _tmp97 {
		goto BB27
	} else {
		goto BB28
	}
BB26:
	_tmp95 = s_S_QUANTITY + 91
	_tmp96 = _tmp95 - qty
	s_S_QUANTITY = _tmp96
	goto BB25
BB27:
	_tmp98 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp98
	goto BB28
BB28:
	_tmp99 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp99
	_tmp100 = float32(qty)
	_tmp101 = s_S_YTD + _tmp100
	s_S_YTD = _tmp101
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop3 lowers hop 3 containing 6 basic block(s).
func NeworderHop3(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp102 uint64
	var sup_w_id uint64
	var _tmp103 uint64
	var qty uint64
	var _tmp104 uint64
	var _tmp105 bool
	var _tmp106 bool
	var _tmp107 bool
	var price float32
	var _tmp109 float32
	var _tmp110 []float32
	var _tmp111 uint64
	var _tmp112 bool
	var _tmp113 uint64
	var _tmp114 uint64
	var _tmp115 uint64
	var _tmp116 bool
	var _tmp117 uint64
	var _tmp118 uint64
	var _tmp119 float32
	var _tmp120 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB29

BB29:
	_tmp102 = listGet(itemIDs, int(2))
	i_id = _tmp102
	_tmp103 = listGet(supplierWarehouseIDs, int(2))
	sup_w_id = _tmp103
	_tmp104 = listGet(orderQuantities, int(2))
	qty = _tmp104
	_tmp105 = qty >= 0
	_tmp106 = qty <= 10
	_tmp107 = _tmp105 && _tmp106
	if !(_tmp107) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp109 = row2.I_PRICE
	price = _tmp109
	_tmp110 = append(prices, price)
	prices = _tmp110
	_tmp111 = s_S_QUANTITY - qty
	_tmp112 = _tmp111 >= 10
	if _tmp112 {
		goto BB30
	} else {
		goto BB32
	}
BB30:
	_tmp113 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp113
	goto BB31
BB31:
	_tmp116 = sup_w_id != w_id
	if _tmp116 {
		goto BB33
	} else {
		goto BB34
	}
BB32:
	_tmp114 = s_S_QUANTITY + 91
	_tmp115 = _tmp114 - qty
	s_S_QUANTITY = _tmp115
	goto BB31
BB33:
	_tmp117 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp117
	goto BB34
BB34:
	_tmp118 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp118
	_tmp119 = float32(qty)
	_tmp120 = s_S_YTD + _tmp119
	s_S_YTD = _tmp120
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop4 lowers hop 4 containing 6 basic block(s).
func NeworderHop4(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp121 uint64
	var sup_w_id uint64
	var _tmp122 uint64
	var qty uint64
	var _tmp123 uint64
	var _tmp124 bool
	var _tmp125 bool
	var _tmp126 bool
	var price float32
	var _tmp128 float32
	var _tmp129 []float32
	var _tmp130 uint64
	var _tmp131 bool
	var _tmp132 uint64
	var _tmp133 uint64
	var _tmp134 uint64
	var _tmp135 bool
	var _tmp136 uint64
	var _tmp137 uint64
	var _tmp138 float32
	var _tmp139 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB35

BB35:
	_tmp121 = listGet(itemIDs, int(3))
	i_id = _tmp121
	_tmp122 = listGet(supplierWarehouseIDs, int(3))
	sup_w_id = _tmp122
	_tmp123 = listGet(orderQuantities, int(3))
	qty = _tmp123
	_tmp124 = qty >= 0
	_tmp125 = qty <= 10
	_tmp126 = _tmp124 && _tmp125
	if !(_tmp126) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp128 = row2.I_PRICE
	price = _tmp128
	_tmp129 = append(prices, price)
	prices = _tmp129
	_tmp130 = s_S_QUANTITY - qty
	_tmp131 = _tmp130 >= 10
	if _tmp131 {
		goto BB36
	} else {
		goto BB38
	}
BB36:
	_tmp132 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp132
	goto BB37
BB37:
	_tmp135 = sup_w_id != w_id
	if _tmp135 {
		goto BB39
	} else {
		goto BB40
	}
BB38:
	_tmp133 = s_S_QUANTITY + 91
	_tmp134 = _tmp133 - qty
	s_S_QUANTITY = _tmp134
	goto BB37
BB39:
	_tmp136 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp136
	goto BB40
BB40:
	_tmp137 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp137
	_tmp138 = float32(qty)
	_tmp139 = s_S_YTD + _tmp138
	s_S_YTD = _tmp139
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop5 lowers hop 5 containing 6 basic block(s).
func NeworderHop5(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp140 uint64
	var sup_w_id uint64
	var _tmp141 uint64
	var qty uint64
	var _tmp142 uint64
	var _tmp143 bool
	var _tmp144 bool
	var _tmp145 bool
	var price float32
	var _tmp147 float32
	var _tmp148 []float32
	var _tmp149 uint64
	var _tmp150 bool
	var _tmp151 uint64
	var _tmp152 uint64
	var _tmp153 uint64
	var _tmp154 bool
	var _tmp155 uint64
	var _tmp156 uint64
	var _tmp157 float32
	var _tmp158 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB41

BB41:
	_tmp140 = listGet(itemIDs, int(4))
	i_id = _tmp140
	_tmp141 = listGet(supplierWarehouseIDs, int(4))
	sup_w_id = _tmp141
	_tmp142 = listGet(orderQuantities, int(4))
	qty = _tmp142
	_tmp143 = qty >= 0
	_tmp144 = qty <= 10
	_tmp145 = _tmp143 && _tmp144
	if !(_tmp145) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp147 = row2.I_PRICE
	price = _tmp147
	_tmp148 = append(prices, price)
	prices = _tmp148
	_tmp149 = s_S_QUANTITY - qty
	_tmp150 = _tmp149 >= 10
	if _tmp150 {
		goto BB42
	} else {
		goto BB44
	}
BB42:
	_tmp151 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp151
	goto BB43
BB43:
	_tmp154 = sup_w_id != w_id
	if _tmp154 {
		goto BB45
	} else {
		goto BB46
	}
BB44:
	_tmp152 = s_S_QUANTITY + 91
	_tmp153 = _tmp152 - qty
	s_S_QUANTITY = _tmp153
	goto BB43
BB45:
	_tmp155 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp155
	goto BB46
BB46:
	_tmp156 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp156
	_tmp157 = float32(qty)
	_tmp158 = s_S_YTD + _tmp157
	s_S_YTD = _tmp158
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop6 lowers hop 6 containing 6 basic block(s).
func NeworderHop6(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp159 uint64
	var sup_w_id uint64
	var _tmp160 uint64
	var qty uint64
	var _tmp161 uint64
	var _tmp162 bool
	var _tmp163 bool
	var _tmp164 bool
	var price float32
	var _tmp166 float32
	var _tmp167 []float32
	var _tmp168 uint64
	var _tmp169 bool
	var _tmp170 uint64
	var _tmp171 uint64
	var _tmp172 uint64
	var _tmp173 bool
	var _tmp174 uint64
	var _tmp175 uint64
	var _tmp176 float32
	var _tmp177 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB47

BB47:
	_tmp159 = listGet(itemIDs, int(5))
	i_id = _tmp159
	_tmp160 = listGet(supplierWarehouseIDs, int(5))
	sup_w_id = _tmp160
	_tmp161 = listGet(orderQuantities, int(5))
	qty = _tmp161
	_tmp162 = qty >= 0
	_tmp163 = qty <= 10
	_tmp164 = _tmp162 && _tmp163
	if !(_tmp164) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp166 = row2.I_PRICE
	price = _tmp166
	_tmp167 = append(prices, price)
	prices = _tmp167
	_tmp168 = s_S_QUANTITY - qty
	_tmp169 = _tmp168 >= 10
	if _tmp169 {
		goto BB48
	} else {
		goto BB50
	}
BB48:
	_tmp170 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp170
	goto BB49
BB49:
	_tmp173 = sup_w_id != w_id
	if _tmp173 {
		goto BB51
	} else {
		goto BB52
	}
BB50:
	_tmp171 = s_S_QUANTITY + 91
	_tmp172 = _tmp171 - qty
	s_S_QUANTITY = _tmp172
	goto BB49
BB51:
	_tmp174 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp174
	goto BB52
BB52:
	_tmp175 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp175
	_tmp176 = float32(qty)
	_tmp177 = s_S_YTD + _tmp176
	s_S_YTD = _tmp177
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop7 lowers hop 7 containing 6 basic block(s).
func NeworderHop7(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp178 uint64
	var sup_w_id uint64
	var _tmp179 uint64
	var qty uint64
	var _tmp180 uint64
	var _tmp181 bool
	var _tmp182 bool
	var _tmp183 bool
	var price float32
	var _tmp185 float32
	var _tmp186 []float32
	var _tmp187 uint64
	var _tmp188 bool
	var _tmp189 uint64
	var _tmp190 uint64
	var _tmp191 uint64
	var _tmp192 bool
	var _tmp193 uint64
	var _tmp194 uint64
	var _tmp195 float32
	var _tmp196 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB53

BB53:
	_tmp178 = listGet(itemIDs, int(6))
	i_id = _tmp178
	_tmp179 = listGet(supplierWarehouseIDs, int(6))
	sup_w_id = _tmp179
	_tmp180 = listGet(orderQuantities, int(6))
	qty = _tmp180
	_tmp181 = qty >= 0
	_tmp182 = qty <= 10
	_tmp183 = _tmp181 && _tmp182
	if !(_tmp183) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp185 = row2.I_PRICE
	price = _tmp185
	_tmp186 = append(prices, price)
	prices = _tmp186
	_tmp187 = s_S_QUANTITY - qty
	_tmp188 = _tmp187 >= 10
	if _tmp188 {
		goto BB54
	} else {
		goto BB56
	}
BB54:
	_tmp189 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp189
	goto BB55
BB55:
	_tmp192 = sup_w_id != w_id
	if _tmp192 {
		goto BB57
	} else {
		goto BB58
	}
BB56:
	_tmp190 = s_S_QUANTITY + 91
	_tmp191 = _tmp190 - qty
	s_S_QUANTITY = _tmp191
	goto BB55
BB57:
	_tmp193 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp193
	goto BB58
BB58:
	_tmp194 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp194
	_tmp195 = float32(qty)
	_tmp196 = s_S_YTD + _tmp195
	s_S_YTD = _tmp196
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop8 lowers hop 8 containing 6 basic block(s).
func NeworderHop8(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp197 uint64
	var sup_w_id uint64
	var _tmp198 uint64
	var qty uint64
	var _tmp199 uint64
	var _tmp200 bool
	var _tmp201 bool
	var _tmp202 bool
	var price float32
	var _tmp204 float32
	var _tmp205 []float32
	var _tmp206 uint64
	var _tmp207 bool
	var _tmp208 uint64
	var _tmp209 uint64
	var _tmp210 uint64
	var _tmp211 bool
	var _tmp212 uint64
	var _tmp213 uint64
	var _tmp214 float32
	var _tmp215 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB59

BB59:
	_tmp197 = listGet(itemIDs, int(7))
	i_id = _tmp197
	_tmp198 = listGet(supplierWarehouseIDs, int(7))
	sup_w_id = _tmp198
	_tmp199 = listGet(orderQuantities, int(7))
	qty = _tmp199
	_tmp200 = qty >= 0
	_tmp201 = qty <= 10
	_tmp202 = _tmp200 && _tmp201
	if !(_tmp202) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp204 = row2.I_PRICE
	price = _tmp204
	_tmp205 = append(prices, price)
	prices = _tmp205
	_tmp206 = s_S_QUANTITY - qty
	_tmp207 = _tmp206 >= 10
	if _tmp207 {
		goto BB60
	} else {
		goto BB62
	}
BB60:
	_tmp208 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp208
	goto BB61
BB61:
	_tmp211 = sup_w_id != w_id
	if _tmp211 {
		goto BB63
	} else {
		goto BB64
	}
BB62:
	_tmp209 = s_S_QUANTITY + 91
	_tmp210 = _tmp209 - qty
	s_S_QUANTITY = _tmp210
	goto BB61
BB63:
	_tmp212 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp212
	goto BB64
BB64:
	_tmp213 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp213
	_tmp214 = float32(qty)
	_tmp215 = s_S_YTD + _tmp214
	s_S_YTD = _tmp215
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop9 lowers hop 9 containing 6 basic block(s).
func NeworderHop9(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp216 uint64
	var sup_w_id uint64
	var _tmp217 uint64
	var qty uint64
	var _tmp218 uint64
	var _tmp219 bool
	var _tmp220 bool
	var _tmp221 bool
	var price float32
	var _tmp223 float32
	var _tmp224 []float32
	var _tmp225 uint64
	var _tmp226 bool
	var _tmp227 uint64
	var _tmp228 uint64
	var _tmp229 uint64
	var _tmp230 bool
	var _tmp231 uint64
	var _tmp232 uint64
	var _tmp233 float32
	var _tmp234 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB65

BB65:
	_tmp216 = listGet(itemIDs, int(8))
	i_id = _tmp216
	_tmp217 = listGet(supplierWarehouseIDs, int(8))
	sup_w_id = _tmp217
	_tmp218 = listGet(orderQuantities, int(8))
	qty = _tmp218
	_tmp219 = qty >= 0
	_tmp220 = qty <= 10
	_tmp221 = _tmp219 && _tmp220
	if !(_tmp221) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp223 = row2.I_PRICE
	price = _tmp223
	_tmp224 = append(prices, price)
	prices = _tmp224
	_tmp225 = s_S_QUANTITY - qty
	_tmp226 = _tmp225 >= 10
	if _tmp226 {
		goto BB66
	} else {
		goto BB68
	}
BB66:
	_tmp227 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp227
	goto BB67
BB67:
	_tmp230 = sup_w_id != w_id
	if _tmp230 {
		goto BB69
	} else {
		goto BB70
	}
BB68:
	_tmp228 = s_S_QUANTITY + 91
	_tmp229 = _tmp228 - qty
	s_S_QUANTITY = _tmp229
	goto BB67
BB69:
	_tmp231 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp231
	goto BB70
BB70:
	_tmp232 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp232
	_tmp233 = float32(qty)
	_tmp234 = s_S_YTD + _tmp233
	s_S_YTD = _tmp234
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop10 lowers hop 10 containing 6 basic block(s).
func NeworderHop10(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp235 uint64
	var sup_w_id uint64
	var _tmp236 uint64
	var qty uint64
	var _tmp237 uint64
	var _tmp238 bool
	var _tmp239 bool
	var _tmp240 bool
	var price float32
	var _tmp242 float32
	var _tmp243 []float32
	var _tmp244 uint64
	var _tmp245 bool
	var _tmp246 uint64
	var _tmp247 uint64
	var _tmp248 uint64
	var _tmp249 bool
	var _tmp250 uint64
	var _tmp251 uint64
	var _tmp252 float32
	var _tmp253 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB71

BB71:
	_tmp235 = listGet(itemIDs, int(9))
	i_id = _tmp235
	_tmp236 = listGet(supplierWarehouseIDs, int(9))
	sup_w_id = _tmp236
	_tmp237 = listGet(orderQuantities, int(9))
	qty = _tmp237
	_tmp238 = qty >= 0
	_tmp239 = qty <= 10
	_tmp240 = _tmp238 && _tmp239
	if !(_tmp240) {
		panic("Assertion failed")
	}
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp242 = row2.I_PRICE
	price = _tmp242
	_tmp243 = append(prices, price)
	prices = _tmp243
	_tmp244 = s_S_QUANTITY - qty
	_tmp245 = _tmp244 >= 10
	if _tmp245 {
		goto BB72
	} else {
		goto BB74
	}
BB72:
	_tmp246 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp246
	goto BB73
BB73:
	_tmp249 = sup_w_id != w_id
	if _tmp249 {
		goto BB75
	} else {
		goto BB76
	}
BB74:
	_tmp247 = s_S_QUANTITY + 91
	_tmp248 = _tmp247 - qty
	s_S_QUANTITY = _tmp248
	goto BB73
BB75:
	_tmp250 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp250
	goto BB76
BB76:
	_tmp251 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp251
	_tmp252 = float32(qty)
	_tmp253 = s_S_YTD + _tmp252
	s_S_YTD = _tmp253
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Write back variables to results
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		Results: []string{string(mustJSON(prices))},
		RWSets: rwSet,
	}, nil
}

// NeworderHop11 lowers hop 11 containing 4 basic block(s).
func NeworderHop11(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var d_id uint64
	var c_id uint64
	var o_all_local uint64
	var date uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var w_tax float32
	var prices []float32
	var d_next_oid uint64
	var _tmp254 uint64
	var _tmp256 uint64
	var ol_number uint64
	var _tmp257 bool
	var i_id uint64
	var _tmp258 uint64
	var sup_w_id uint64
	var _tmp259 uint64
	var qty uint64
	var _tmp260 uint64
	var price float32
	var _tmp261 float32
	var _tmp262 float32
	var _tmp263 float32
	var _tmp264 uint64
	var _tmp265 uint64
	var _tmp266 Unit

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 OrderLine
	var keyBytes5 []byte
	var row5 OrderLine

	w_id = toUint64(params["w_id"])
	d_id = toUint64(params["d_id"])
	c_id = toUint64(params["c_id"])
	o_all_local = toUint64(params["o_all_local"])
	date = toUint64(params["date"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	w_tax = toFloat32(params["w_tax"])
	json.Unmarshal([]byte(params["prices"]), &prices)

	goto BB77

BB77:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp254 = row1.D_NEXT_O_ID
	d_next_oid = _tmp254
	_tmp256 = d_next_oid + 1
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_O_ID = _tmp256
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id}, row2)
	// Optimized combined table access: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: d_id, O_ID: d_next_oid})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	row3.O_C_ID = c_id
	row3.O_ENTRY_DATE = date
	row3.O_OL_CNT = O_OL_CNT
	row3.O_ALL_LOCAL = o_all_local
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: d_id, O_ID: d_next_oid}, row3)
	ol_number = 0
	goto BB78
BB78:
	_tmp257 = ol_number < O_OL_CNT
	if _tmp257 {
		goto BB79
	} else {
		goto BB81
	}
BB79:
	_tmp258 = listGet(itemIDs, int(ol_number))
	i_id = _tmp258
	_tmp259 = listGet(supplierWarehouseIDs, int(ol_number))
	sup_w_id = _tmp259
	_tmp260 = listGet(orderQuantities, int(ol_number))
	qty = _tmp260
	_tmp261 = listGet(prices, int(ol_number))
	price = _tmp261
	// Optimized combined table access: OrderLine
	keyBytes4, row4 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes4)
	row4.OL_I_ID = i_id
	row4.OL_SUPPLY_W_ID = sup_w_id
	row4.OL_QUANTITY = qty
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number}, row4)
	_tmp262 = float32(qty)
	_tmp263 = price * _tmp262
	_tmp264 = uint64(_tmp263)
	// TableSet: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_AMOUNT = _tmp264
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number}, row5)
	_tmp265 = ol_number + 1
	ol_number = _tmp265
	goto BB78
BB81:
	to_unit[float32](w_tax, &_tmp266)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// NeworderHop0Par calculates the partition for hop 0 without database access.
func NeworderHop0Par(params map[string]string) uint64 {
	var w_id uint64
	var w_tax float32
	var _tmp62 float32
	var prices []float32
	var _tmp63 []float32

	var keyBytes1 []byte
	var row1 Warehouse

	w_id = toUint64(params["w_id"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB16

BB16:
	// First table access - calculate partition: Warehouse
	if true { return getWarehousePar(WarehouseKey{W_ID: w_id}) }
	// TableGet: Warehouse
	keyBytes1, row1 = getWarehouse(tx, WarehouseKey{W_ID: w_id})
	rwSet = AddRWSet(rwSet, "Warehouse", keyBytes1)
	_tmp62 = row1.W_TAX
	w_tax = _tmp62
	_tmp63 = nil
	prices = _tmp63
	// Unreachable: use variables in results
	_ = []string{fromFloat32(w_tax), string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop1Par calculates the partition for hop 1 without database access.
func NeworderHop1Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var i_id uint64
	var _tmp64 uint64
	var sup_w_id uint64
	var _tmp65 uint64
	var qty uint64
	var _tmp66 uint64
	var _tmp67 bool
	var _tmp68 bool
	var _tmp69 bool
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var price float32
	var _tmp71 float32
	var _tmp72 []float32
	var _tmp73 uint64
	var _tmp74 bool
	var _tmp75 uint64
	var _tmp76 uint64
	var _tmp77 uint64
	var _tmp78 bool
	var _tmp79 uint64
	var _tmp80 uint64
	var _tmp81 float32
	var _tmp82 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB17

BB17:
	_tmp64 = listGet(itemIDs, int(0))
	i_id = _tmp64
	_tmp65 = listGet(supplierWarehouseIDs, int(0))
	sup_w_id = _tmp65
	_tmp66 = listGet(orderQuantities, int(0))
	qty = _tmp66
	_tmp67 = qty >= 0
	_tmp68 = qty <= 10
	_tmp69 = _tmp67 && _tmp68
	if !(_tmp69) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp71 = row2.I_PRICE
	price = _tmp71
	_tmp72 = append(prices, price)
	prices = _tmp72
	_tmp73 = s_S_QUANTITY - qty
	_tmp74 = _tmp73 >= 10
	if _tmp74 {
		goto BB18
	} else {
		goto BB20
	}
BB18:
	_tmp75 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp75
	goto BB19
BB19:
	_tmp78 = sup_w_id != w_id
	if _tmp78 {
		goto BB21
	} else {
		goto BB22
	}
BB20:
	_tmp76 = s_S_QUANTITY + 91
	_tmp77 = _tmp76 - qty
	s_S_QUANTITY = _tmp77
	goto BB19
BB21:
	_tmp79 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp79
	goto BB22
BB22:
	_tmp80 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp80
	_tmp81 = float32(qty)
	_tmp82 = s_S_YTD + _tmp81
	s_S_YTD = _tmp82
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop2Par calculates the partition for hop 2 without database access.
func NeworderHop2Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp83 uint64
	var sup_w_id uint64
	var _tmp84 uint64
	var qty uint64
	var _tmp85 uint64
	var _tmp86 bool
	var _tmp87 bool
	var _tmp88 bool
	var price float32
	var _tmp90 float32
	var _tmp91 []float32
	var _tmp92 uint64
	var _tmp93 bool
	var _tmp94 uint64
	var _tmp95 uint64
	var _tmp96 uint64
	var _tmp97 bool
	var _tmp98 uint64
	var _tmp99 uint64
	var _tmp100 float32
	var _tmp101 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB23

BB23:
	_tmp83 = listGet(itemIDs, int(1))
	i_id = _tmp83
	_tmp84 = listGet(supplierWarehouseIDs, int(1))
	sup_w_id = _tmp84
	_tmp85 = listGet(orderQuantities, int(1))
	qty = _tmp85
	_tmp86 = qty >= 0
	_tmp87 = qty <= 10
	_tmp88 = _tmp86 && _tmp87
	if !(_tmp88) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp90 = row2.I_PRICE
	price = _tmp90
	_tmp91 = append(prices, price)
	prices = _tmp91
	_tmp92 = s_S_QUANTITY - qty
	_tmp93 = _tmp92 >= 10
	if _tmp93 {
		goto BB24
	} else {
		goto BB26
	}
BB24:
	_tmp94 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp94
	goto BB25
BB25:
	_tmp97 = sup_w_id != w_id
	if _tmp97 {
		goto BB27
	} else {
		goto BB28
	}
BB26:
	_tmp95 = s_S_QUANTITY + 91
	_tmp96 = _tmp95 - qty
	s_S_QUANTITY = _tmp96
	goto BB25
BB27:
	_tmp98 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp98
	goto BB28
BB28:
	_tmp99 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp99
	_tmp100 = float32(qty)
	_tmp101 = s_S_YTD + _tmp100
	s_S_YTD = _tmp101
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop3Par calculates the partition for hop 3 without database access.
func NeworderHop3Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp102 uint64
	var sup_w_id uint64
	var _tmp103 uint64
	var qty uint64
	var _tmp104 uint64
	var _tmp105 bool
	var _tmp106 bool
	var _tmp107 bool
	var price float32
	var _tmp109 float32
	var _tmp110 []float32
	var _tmp111 uint64
	var _tmp112 bool
	var _tmp113 uint64
	var _tmp114 uint64
	var _tmp115 uint64
	var _tmp116 bool
	var _tmp117 uint64
	var _tmp118 uint64
	var _tmp119 float32
	var _tmp120 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB29

BB29:
	_tmp102 = listGet(itemIDs, int(2))
	i_id = _tmp102
	_tmp103 = listGet(supplierWarehouseIDs, int(2))
	sup_w_id = _tmp103
	_tmp104 = listGet(orderQuantities, int(2))
	qty = _tmp104
	_tmp105 = qty >= 0
	_tmp106 = qty <= 10
	_tmp107 = _tmp105 && _tmp106
	if !(_tmp107) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp109 = row2.I_PRICE
	price = _tmp109
	_tmp110 = append(prices, price)
	prices = _tmp110
	_tmp111 = s_S_QUANTITY - qty
	_tmp112 = _tmp111 >= 10
	if _tmp112 {
		goto BB30
	} else {
		goto BB32
	}
BB30:
	_tmp113 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp113
	goto BB31
BB31:
	_tmp116 = sup_w_id != w_id
	if _tmp116 {
		goto BB33
	} else {
		goto BB34
	}
BB32:
	_tmp114 = s_S_QUANTITY + 91
	_tmp115 = _tmp114 - qty
	s_S_QUANTITY = _tmp115
	goto BB31
BB33:
	_tmp117 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp117
	goto BB34
BB34:
	_tmp118 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp118
	_tmp119 = float32(qty)
	_tmp120 = s_S_YTD + _tmp119
	s_S_YTD = _tmp120
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop4Par calculates the partition for hop 4 without database access.
func NeworderHop4Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp121 uint64
	var sup_w_id uint64
	var _tmp122 uint64
	var qty uint64
	var _tmp123 uint64
	var _tmp124 bool
	var _tmp125 bool
	var _tmp126 bool
	var price float32
	var _tmp128 float32
	var _tmp129 []float32
	var _tmp130 uint64
	var _tmp131 bool
	var _tmp132 uint64
	var _tmp133 uint64
	var _tmp134 uint64
	var _tmp135 bool
	var _tmp136 uint64
	var _tmp137 uint64
	var _tmp138 float32
	var _tmp139 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB35

BB35:
	_tmp121 = listGet(itemIDs, int(3))
	i_id = _tmp121
	_tmp122 = listGet(supplierWarehouseIDs, int(3))
	sup_w_id = _tmp122
	_tmp123 = listGet(orderQuantities, int(3))
	qty = _tmp123
	_tmp124 = qty >= 0
	_tmp125 = qty <= 10
	_tmp126 = _tmp124 && _tmp125
	if !(_tmp126) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp128 = row2.I_PRICE
	price = _tmp128
	_tmp129 = append(prices, price)
	prices = _tmp129
	_tmp130 = s_S_QUANTITY - qty
	_tmp131 = _tmp130 >= 10
	if _tmp131 {
		goto BB36
	} else {
		goto BB38
	}
BB36:
	_tmp132 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp132
	goto BB37
BB37:
	_tmp135 = sup_w_id != w_id
	if _tmp135 {
		goto BB39
	} else {
		goto BB40
	}
BB38:
	_tmp133 = s_S_QUANTITY + 91
	_tmp134 = _tmp133 - qty
	s_S_QUANTITY = _tmp134
	goto BB37
BB39:
	_tmp136 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp136
	goto BB40
BB40:
	_tmp137 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp137
	_tmp138 = float32(qty)
	_tmp139 = s_S_YTD + _tmp138
	s_S_YTD = _tmp139
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop5Par calculates the partition for hop 5 without database access.
func NeworderHop5Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp140 uint64
	var sup_w_id uint64
	var _tmp141 uint64
	var qty uint64
	var _tmp142 uint64
	var _tmp143 bool
	var _tmp144 bool
	var _tmp145 bool
	var price float32
	var _tmp147 float32
	var _tmp148 []float32
	var _tmp149 uint64
	var _tmp150 bool
	var _tmp151 uint64
	var _tmp152 uint64
	var _tmp153 uint64
	var _tmp154 bool
	var _tmp155 uint64
	var _tmp156 uint64
	var _tmp157 float32
	var _tmp158 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB41

BB41:
	_tmp140 = listGet(itemIDs, int(4))
	i_id = _tmp140
	_tmp141 = listGet(supplierWarehouseIDs, int(4))
	sup_w_id = _tmp141
	_tmp142 = listGet(orderQuantities, int(4))
	qty = _tmp142
	_tmp143 = qty >= 0
	_tmp144 = qty <= 10
	_tmp145 = _tmp143 && _tmp144
	if !(_tmp145) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp147 = row2.I_PRICE
	price = _tmp147
	_tmp148 = append(prices, price)
	prices = _tmp148
	_tmp149 = s_S_QUANTITY - qty
	_tmp150 = _tmp149 >= 10
	if _tmp150 {
		goto BB42
	} else {
		goto BB44
	}
BB42:
	_tmp151 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp151
	goto BB43
BB43:
	_tmp154 = sup_w_id != w_id
	if _tmp154 {
		goto BB45
	} else {
		goto BB46
	}
BB44:
	_tmp152 = s_S_QUANTITY + 91
	_tmp153 = _tmp152 - qty
	s_S_QUANTITY = _tmp153
	goto BB43
BB45:
	_tmp155 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp155
	goto BB46
BB46:
	_tmp156 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp156
	_tmp157 = float32(qty)
	_tmp158 = s_S_YTD + _tmp157
	s_S_YTD = _tmp158
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop6Par calculates the partition for hop 6 without database access.
func NeworderHop6Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp159 uint64
	var sup_w_id uint64
	var _tmp160 uint64
	var qty uint64
	var _tmp161 uint64
	var _tmp162 bool
	var _tmp163 bool
	var _tmp164 bool
	var price float32
	var _tmp166 float32
	var _tmp167 []float32
	var _tmp168 uint64
	var _tmp169 bool
	var _tmp170 uint64
	var _tmp171 uint64
	var _tmp172 uint64
	var _tmp173 bool
	var _tmp174 uint64
	var _tmp175 uint64
	var _tmp176 float32
	var _tmp177 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB47

BB47:
	_tmp159 = listGet(itemIDs, int(5))
	i_id = _tmp159
	_tmp160 = listGet(supplierWarehouseIDs, int(5))
	sup_w_id = _tmp160
	_tmp161 = listGet(orderQuantities, int(5))
	qty = _tmp161
	_tmp162 = qty >= 0
	_tmp163 = qty <= 10
	_tmp164 = _tmp162 && _tmp163
	if !(_tmp164) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp166 = row2.I_PRICE
	price = _tmp166
	_tmp167 = append(prices, price)
	prices = _tmp167
	_tmp168 = s_S_QUANTITY - qty
	_tmp169 = _tmp168 >= 10
	if _tmp169 {
		goto BB48
	} else {
		goto BB50
	}
BB48:
	_tmp170 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp170
	goto BB49
BB49:
	_tmp173 = sup_w_id != w_id
	if _tmp173 {
		goto BB51
	} else {
		goto BB52
	}
BB50:
	_tmp171 = s_S_QUANTITY + 91
	_tmp172 = _tmp171 - qty
	s_S_QUANTITY = _tmp172
	goto BB49
BB51:
	_tmp174 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp174
	goto BB52
BB52:
	_tmp175 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp175
	_tmp176 = float32(qty)
	_tmp177 = s_S_YTD + _tmp176
	s_S_YTD = _tmp177
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop7Par calculates the partition for hop 7 without database access.
func NeworderHop7Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp178 uint64
	var sup_w_id uint64
	var _tmp179 uint64
	var qty uint64
	var _tmp180 uint64
	var _tmp181 bool
	var _tmp182 bool
	var _tmp183 bool
	var price float32
	var _tmp185 float32
	var _tmp186 []float32
	var _tmp187 uint64
	var _tmp188 bool
	var _tmp189 uint64
	var _tmp190 uint64
	var _tmp191 uint64
	var _tmp192 bool
	var _tmp193 uint64
	var _tmp194 uint64
	var _tmp195 float32
	var _tmp196 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB53

BB53:
	_tmp178 = listGet(itemIDs, int(6))
	i_id = _tmp178
	_tmp179 = listGet(supplierWarehouseIDs, int(6))
	sup_w_id = _tmp179
	_tmp180 = listGet(orderQuantities, int(6))
	qty = _tmp180
	_tmp181 = qty >= 0
	_tmp182 = qty <= 10
	_tmp183 = _tmp181 && _tmp182
	if !(_tmp183) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp185 = row2.I_PRICE
	price = _tmp185
	_tmp186 = append(prices, price)
	prices = _tmp186
	_tmp187 = s_S_QUANTITY - qty
	_tmp188 = _tmp187 >= 10
	if _tmp188 {
		goto BB54
	} else {
		goto BB56
	}
BB54:
	_tmp189 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp189
	goto BB55
BB55:
	_tmp192 = sup_w_id != w_id
	if _tmp192 {
		goto BB57
	} else {
		goto BB58
	}
BB56:
	_tmp190 = s_S_QUANTITY + 91
	_tmp191 = _tmp190 - qty
	s_S_QUANTITY = _tmp191
	goto BB55
BB57:
	_tmp193 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp193
	goto BB58
BB58:
	_tmp194 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp194
	_tmp195 = float32(qty)
	_tmp196 = s_S_YTD + _tmp195
	s_S_YTD = _tmp196
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop8Par calculates the partition for hop 8 without database access.
func NeworderHop8Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp197 uint64
	var sup_w_id uint64
	var _tmp198 uint64
	var qty uint64
	var _tmp199 uint64
	var _tmp200 bool
	var _tmp201 bool
	var _tmp202 bool
	var price float32
	var _tmp204 float32
	var _tmp205 []float32
	var _tmp206 uint64
	var _tmp207 bool
	var _tmp208 uint64
	var _tmp209 uint64
	var _tmp210 uint64
	var _tmp211 bool
	var _tmp212 uint64
	var _tmp213 uint64
	var _tmp214 float32
	var _tmp215 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB59

BB59:
	_tmp197 = listGet(itemIDs, int(7))
	i_id = _tmp197
	_tmp198 = listGet(supplierWarehouseIDs, int(7))
	sup_w_id = _tmp198
	_tmp199 = listGet(orderQuantities, int(7))
	qty = _tmp199
	_tmp200 = qty >= 0
	_tmp201 = qty <= 10
	_tmp202 = _tmp200 && _tmp201
	if !(_tmp202) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp204 = row2.I_PRICE
	price = _tmp204
	_tmp205 = append(prices, price)
	prices = _tmp205
	_tmp206 = s_S_QUANTITY - qty
	_tmp207 = _tmp206 >= 10
	if _tmp207 {
		goto BB60
	} else {
		goto BB62
	}
BB60:
	_tmp208 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp208
	goto BB61
BB61:
	_tmp211 = sup_w_id != w_id
	if _tmp211 {
		goto BB63
	} else {
		goto BB64
	}
BB62:
	_tmp209 = s_S_QUANTITY + 91
	_tmp210 = _tmp209 - qty
	s_S_QUANTITY = _tmp210
	goto BB61
BB63:
	_tmp212 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp212
	goto BB64
BB64:
	_tmp213 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp213
	_tmp214 = float32(qty)
	_tmp215 = s_S_YTD + _tmp214
	s_S_YTD = _tmp215
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop9Par calculates the partition for hop 9 without database access.
func NeworderHop9Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp216 uint64
	var sup_w_id uint64
	var _tmp217 uint64
	var qty uint64
	var _tmp218 uint64
	var _tmp219 bool
	var _tmp220 bool
	var _tmp221 bool
	var price float32
	var _tmp223 float32
	var _tmp224 []float32
	var _tmp225 uint64
	var _tmp226 bool
	var _tmp227 uint64
	var _tmp228 uint64
	var _tmp229 uint64
	var _tmp230 bool
	var _tmp231 uint64
	var _tmp232 uint64
	var _tmp233 float32
	var _tmp234 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB65

BB65:
	_tmp216 = listGet(itemIDs, int(8))
	i_id = _tmp216
	_tmp217 = listGet(supplierWarehouseIDs, int(8))
	sup_w_id = _tmp217
	_tmp218 = listGet(orderQuantities, int(8))
	qty = _tmp218
	_tmp219 = qty >= 0
	_tmp220 = qty <= 10
	_tmp221 = _tmp219 && _tmp220
	if !(_tmp221) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp223 = row2.I_PRICE
	price = _tmp223
	_tmp224 = append(prices, price)
	prices = _tmp224
	_tmp225 = s_S_QUANTITY - qty
	_tmp226 = _tmp225 >= 10
	if _tmp226 {
		goto BB66
	} else {
		goto BB68
	}
BB66:
	_tmp227 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp227
	goto BB67
BB67:
	_tmp230 = sup_w_id != w_id
	if _tmp230 {
		goto BB69
	} else {
		goto BB70
	}
BB68:
	_tmp228 = s_S_QUANTITY + 91
	_tmp229 = _tmp228 - qty
	s_S_QUANTITY = _tmp229
	goto BB67
BB69:
	_tmp231 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp231
	goto BB70
BB70:
	_tmp232 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp232
	_tmp233 = float32(qty)
	_tmp234 = s_S_YTD + _tmp233
	s_S_YTD = _tmp234
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop10Par calculates the partition for hop 10 without database access.
func NeworderHop10Par(params map[string]string) uint64 {
	var w_id uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var prices []float32
	var s_S_W_ID uint64
	var s_S_I_ID uint64
	var s_S_QUANTITY uint64
	var s_S_YTD float32
	var s_S_ORDER_CNT uint64
	var s_S_REMOTE_CNT uint64
	var s_S_DATA string
	var i_id uint64
	var _tmp235 uint64
	var sup_w_id uint64
	var _tmp236 uint64
	var qty uint64
	var _tmp237 uint64
	var _tmp238 bool
	var _tmp239 bool
	var _tmp240 bool
	var price float32
	var _tmp242 float32
	var _tmp243 []float32
	var _tmp244 uint64
	var _tmp245 bool
	var _tmp246 uint64
	var _tmp247 uint64
	var _tmp248 uint64
	var _tmp249 bool
	var _tmp250 uint64
	var _tmp251 uint64
	var _tmp252 float32
	var _tmp253 float32

	var keyBytes1 []byte
	var row1 Stock
	var keyBytes2 []byte
	var row2 Item
	var keyBytes3 []byte
	var row3 Stock

	w_id = toUint64(params["w_id"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB71

BB71:
	_tmp235 = listGet(itemIDs, int(9))
	i_id = _tmp235
	_tmp236 = listGet(supplierWarehouseIDs, int(9))
	sup_w_id = _tmp236
	_tmp237 = listGet(orderQuantities, int(9))
	qty = _tmp237
	_tmp238 = qty >= 0
	_tmp239 = qty <= 10
	_tmp240 = _tmp238 && _tmp239
	if !(_tmp240) {
		panic("Assertion failed")
	}
	// First table access (optimized group) - calculate partition: Stock
	if true { return getStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes1, row1 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes1)
	s_S_REMOTE_CNT = row1.S_REMOTE_CNT
	s_S_DATA = row1.S_DATA
	s_S_I_ID = row1.Key.S_I_ID
	s_S_YTD = row1.S_YTD
	s_S_ORDER_CNT = row1.S_ORDER_CNT
	s_S_QUANTITY = row1.S_QUANTITY
	s_S_W_ID = row1.Key.S_W_ID
	// First table access - calculate partition: Item
	if true { return getItemPar(ItemKey{I_ID: i_id, W_ID: sup_w_id}) }
	// TableGet: Item
	keyBytes2, row2 = getItem(tx, ItemKey{I_ID: i_id, W_ID: sup_w_id})
	rwSet = AddRWSet(rwSet, "Item", keyBytes2)
	_tmp242 = row2.I_PRICE
	price = _tmp242
	_tmp243 = append(prices, price)
	prices = _tmp243
	_tmp244 = s_S_QUANTITY - qty
	_tmp245 = _tmp244 >= 10
	if _tmp245 {
		goto BB72
	} else {
		goto BB74
	}
BB72:
	_tmp246 = s_S_QUANTITY - qty
	s_S_QUANTITY = _tmp246
	goto BB73
BB73:
	_tmp249 = sup_w_id != w_id
	if _tmp249 {
		goto BB75
	} else {
		goto BB76
	}
BB74:
	_tmp247 = s_S_QUANTITY + 91
	_tmp248 = _tmp247 - qty
	s_S_QUANTITY = _tmp248
	goto BB73
BB75:
	_tmp250 = s_S_REMOTE_CNT + 1
	s_S_REMOTE_CNT = _tmp250
	goto BB76
BB76:
	_tmp251 = s_S_ORDER_CNT + 1
	s_S_ORDER_CNT = _tmp251
	_tmp252 = float32(qty)
	_tmp253 = s_S_YTD + _tmp252
	s_S_YTD = _tmp253
	// First table access (optimized group) - calculate partition: Stock
	if true { return putStockPar(StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}) }
	// Optimized combined table access: Stock
	keyBytes3, row3 = getStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id})
	rwSet = AddRWSet(rwSet, "Stock", keyBytes3)
	row3.S_REMOTE_CNT = s_S_REMOTE_CNT
	row3.S_DATA = s_S_DATA
	row3.Key.S_I_ID = s_S_I_ID
	row3.S_YTD = s_S_YTD
	row3.S_ORDER_CNT = s_S_ORDER_CNT
	row3.S_QUANTITY = s_S_QUANTITY
	row3.Key.S_W_ID = s_S_W_ID
	putStock(tx, StockKey{S_W_ID: sup_w_id, S_I_ID: i_id}, row3)
	// Unreachable: use variables in results
	_ = []string{string(mustJSON(prices))}
	panic("unexpected hop exit in partition")
}

// NeworderHop11Par calculates the partition for hop 11 without database access.
func NeworderHop11Par(params map[string]string) uint64 {
	var w_id uint64
	var d_id uint64
	var c_id uint64
	var o_all_local uint64
	var date uint64
	var itemIDs []uint64
	var supplierWarehouseIDs []uint64
	var orderQuantities []uint64
	var w_tax float32
	var prices []float32
	var d_next_oid uint64
	var _tmp254 uint64
	var _tmp256 uint64
	var ol_number uint64
	var _tmp257 bool
	var i_id uint64
	var _tmp258 uint64
	var sup_w_id uint64
	var _tmp259 uint64
	var qty uint64
	var _tmp260 uint64
	var price float32
	var _tmp261 float32
	var _tmp262 float32
	var _tmp263 float32
	var _tmp264 uint64
	var _tmp265 uint64
	var _tmp266 Unit

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District
	var keyBytes3 []byte
	var row3 Order
	var keyBytes4 []byte
	var row4 OrderLine
	var keyBytes5 []byte
	var row5 OrderLine

	w_id = toUint64(params["w_id"])
	d_id = toUint64(params["d_id"])
	c_id = toUint64(params["c_id"])
	o_all_local = toUint64(params["o_all_local"])
	date = toUint64(params["date"])
	json.Unmarshal([]byte(params["itemIDs"]), &itemIDs)
	json.Unmarshal([]byte(params["supplierWarehouseIDs"]), &supplierWarehouseIDs)
	json.Unmarshal([]byte(params["orderQuantities"]), &orderQuantities)
	w_tax = toFloat32(params["w_tax"])
	json.Unmarshal([]byte(params["prices"]), &prices)

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB77

BB77:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: d_id}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp254 = row1.D_NEXT_O_ID
	d_next_oid = _tmp254
	_tmp256 = d_next_oid + 1
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: d_id}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_NEXT_O_ID = _tmp256
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id}, row2)
	// First table access (optimized group) - calculate partition: Order
	if true { return putOrderPar(OrderKey{O_W_ID: w_id, O_D_ID: d_id, O_ID: d_next_oid}) }
	// Optimized combined table access: Order
	keyBytes3, row3 = getOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: d_id, O_ID: d_next_oid})
	rwSet = AddRWSet(rwSet, "Order", keyBytes3)
	row3.O_C_ID = c_id
	row3.O_ENTRY_DATE = date
	row3.O_OL_CNT = O_OL_CNT
	row3.O_ALL_LOCAL = o_all_local
	putOrder(tx, OrderKey{O_W_ID: w_id, O_D_ID: d_id, O_ID: d_next_oid}, row3)
	ol_number = 0
	goto BB78
BB78:
	_tmp257 = ol_number < O_OL_CNT
	if _tmp257 {
		goto BB79
	} else {
		goto BB81
	}
BB79:
	_tmp258 = listGet(itemIDs, int(ol_number))
	i_id = _tmp258
	_tmp259 = listGet(supplierWarehouseIDs, int(ol_number))
	sup_w_id = _tmp259
	_tmp260 = listGet(orderQuantities, int(ol_number))
	qty = _tmp260
	_tmp261 = listGet(prices, int(ol_number))
	price = _tmp261
	// First table access (optimized group) - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number}) }
	// Optimized combined table access: OrderLine
	keyBytes4, row4 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes4)
	row4.OL_I_ID = i_id
	row4.OL_SUPPLY_W_ID = sup_w_id
	row4.OL_QUANTITY = qty
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number}, row4)
	_tmp262 = float32(qty)
	_tmp263 = price * _tmp262
	_tmp264 = uint64(_tmp263)
	// First table access - calculate partition: OrderLine
	if true { return putOrderLinePar(OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number}) }
	// TableSet: OrderLine
	keyBytes5, row5 = getOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number})
	rwSet = AddRWSet(rwSet, "OrderLine", keyBytes5)
	row5.OL_AMOUNT = _tmp264
	putOrderLine(tx, OrderLineKey{OL_W_ID: w_id, OL_D_ID: d_id, OL_O_ID: d_next_oid, OL_NUMBER: ol_number}, row5)
	_tmp265 = ol_number + 1
	ol_number = _tmp265
	goto BB78
BB81:
	to_unit[float32](w_tax, &_tmp266)
	return 0
}

func NeworderNextReq(in *proto.TrxRes, params map[string]string, shards int) (*proto.TrxReq, map[string]string, int) {
	hopId := in.Info.Hopid
	req := &proto.TrxReq{Info: in.Info}
	nextShard := 0

	switch hopId {
	case 0:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop0Par(paramsCopy))
	case 1:
		// Extract variables from previous hop results
		params["w_tax"] = in.Results[0]
		params["prices"] = in.Results[1]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop1Par(paramsCopy))
	case 2:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop2Par(paramsCopy))
	case 3:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop3Par(paramsCopy))
	case 4:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop4Par(paramsCopy))
	case 5:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop5Par(paramsCopy))
	case 6:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop6Par(paramsCopy))
	case 7:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop7Par(paramsCopy))
	case 8:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop8Par(paramsCopy))
	case 9:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop9Par(paramsCopy))
	case 10:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop10Par(paramsCopy))
	case 11:
		// Extract variables from previous hop results
		params["prices"] = in.Results[0]
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(NeworderHop11Par(paramsCopy))
	default:
		return nil, params, 0
	}

	req.Params = params
	req.Info.Hopid += 1
	req.Dependency = in.Dependency
	return req, params, nextShard
}

func NeworderChainImpl(db *bolt.DB) *Chain {
	// Create the list of hops
	hops := make([]*Hop, 12)

	hops[0] = &Hop{
		id:         0,
		hopType:    util.NormalHop,
		isReadOnly: true,
		process:    NeworderHop0,
		conflicts:  map[int32]int32{},
	}

	hops[1] = &Hop{
		id:         1,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop1,
		conflicts:  map[int32]int32{},
	}

	hops[2] = &Hop{
		id:         2,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop2,
		conflicts:  map[int32]int32{},
	}

	hops[3] = &Hop{
		id:         3,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop3,
		conflicts:  map[int32]int32{},
	}

	hops[4] = &Hop{
		id:         4,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop4,
		conflicts:  map[int32]int32{},
	}

	hops[5] = &Hop{
		id:         5,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop5,
		conflicts:  map[int32]int32{},
	}

	hops[6] = &Hop{
		id:         6,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop6,
		conflicts:  map[int32]int32{},
	}

	hops[7] = &Hop{
		id:         7,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop7,
		conflicts:  map[int32]int32{},
	}

	hops[8] = &Hop{
		id:         8,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop8,
		conflicts:  map[int32]int32{},
	}

	hops[9] = &Hop{
		id:         9,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop9,
		conflicts:  map[int32]int32{},
	}

	hops[10] = &Hop{
		id:         10,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop10,
		conflicts:  map[int32]int32{},
	}

	hops[11] = &Hop{
		id:         11,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop11,
		conflicts:  map[int32]int32{0: 11, 1: 0},
	}

	// add field names
	return &Chain{db: db, hops: hops, NextReq: NeworderNextReq}
}

func NeworderChainPreOptImpl(db *bolt.DB) *Chain {
	// Create the list of hops
	hops := make([]*Hop, 12)

	hops[0] = &Hop{
		id:         0,
		hopType:    util.NormalHop,
		isReadOnly: true,
		process:    NeworderHop0,
		conflicts:  map[int32]int32{},
	}

	hops[1] = &Hop{
		id:         1,
		hopType:    util.MergedHopBegin,
		isReadOnly: false,
		process:    NeworderHop1,
		conflicts:  map[int32]int32{0:1},
	}

	hops[2] = &Hop{
		id:         2,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    NeworderHop2,
		conflicts:  map[int32]int32{0:1},
	}

	hops[3] = &Hop{
		id:         3,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    NeworderHop3,
		conflicts:  map[int32]int32{0:1},
	}

	hops[4] = &Hop{
		id:         4,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    NeworderHop4,
		conflicts:  map[int32]int32{0:1},
	}

	hops[5] = &Hop{
		id:         5,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    NeworderHop5,
		conflicts:  map[int32]int32{0:1},
	}

	hops[6] = &Hop{
		id:         6,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    NeworderHop6,
		conflicts:  map[int32]int32{0:1},
	}

	hops[7] = &Hop{
		id:         7,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    NeworderHop7,
		conflicts:  map[int32]int32{0:1},
	}

	hops[8] = &Hop{
		id:         8,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    NeworderHop8,
		conflicts:  map[int32]int32{0:1},
	}

	hops[9] = &Hop{
		id:         9,
		hopType:    util.MergedHop,
		isReadOnly: false,
		process:    NeworderHop9,
		conflicts:  map[int32]int32{0:1},
	}

	hops[10] = &Hop{
		id:         10,
		hopType:    util.MergedHopEnd,
		isReadOnly: false,
		process:    NeworderHop10,
		conflicts:  map[int32]int32{0:1},
	}

	hops[11] = &Hop{
		id:         11,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    NeworderHop11,
		conflicts:  map[int32]int32{0: 11, 1: 0},
	}

	// add field names
	return &Chain{db: db, hops: hops, NextReq: NeworderNextReq}
}

func NeworderToJSON(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

