// Code generated by FMitF Go code generator. DO NOT EDIT.

package chainManager

import (
	"encoding/json"
	"github.com/boltdb/bolt"
	"ShardDB/proto"
	"ShardDB/util"
)

type PaymentChain struct {
	db   *bolt.DB
	hops []*Hop
}

// PaymentHop0 lowers hop 0 containing 1 basic block(s).
func PaymentHop0(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var amount float32
	var _tmp397 float32
	var _tmp398 float32

	var keyBytes1 []byte
	var row1 Warehouse
	var keyBytes2 []byte
	var row2 Warehouse

	w_id = toUint64(params["w_id"])
	amount = toFloat32(params["amount"])

	goto BB132

BB132:
	// TableGet: Warehouse
	keyBytes1, row1 = getWarehouse(tx, WarehouseKey{W_ID: w_id})
	rwSet = AddRWSet(rwSet, "Warehouse", keyBytes1)
	_tmp397 = row1.W_YTD
	_tmp398 = _tmp397 + amount
	// TableSet: Warehouse
	keyBytes2, row2 = getWarehouse(tx, WarehouseKey{W_ID: w_id})
	rwSet = AddRWSet(rwSet, "Warehouse", keyBytes2)
	row2.W_YTD = _tmp398
	putWarehouse(tx, WarehouseKey{W_ID: w_id}, row2)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// PaymentHop1 lowers hop 1 containing 1 basic block(s).
func PaymentHop1(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var d_id uint64
	var amount float32
	var _tmp399 float32
	var _tmp400 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District

	w_id = toUint64(params["w_id"])
	d_id = toUint64(params["d_id"])
	amount = toFloat32(params["amount"])

	goto BB133

BB133:
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp399 = row1.D_YTD
	_tmp400 = _tmp399 + amount
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_YTD = _tmp400
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id}, row2)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// PaymentHop2 lowers hop 2 containing 3 basic block(s).
func PaymentHop2(tx *bolt.Tx, in *proto.TrxReq) (*proto.TrxRes, error) {
	var rwSet []*proto.RWSet
	params := in.Params

	var w_id uint64
	var d_id uint64
	var c_w_id uint64
	var c_d_id uint64
	var c_id uint64
	var amount float32
	var c_C_W_ID uint64
	var c_C_D_ID uint64
	var c_C_ID uint64
	var c_C_FIRST string
	var c_C_MIDDLE string
	var c_C_LAST string
	var c_C_STREET_1 string
	var c_C_STREET_2 string
	var c_C_CITY string
	var c_C_STATE string
	var c_C_ZIP string
	var c_C_PHONE string
	var c_C_SINCE uint64
	var c_C_CREDIT string
	var c_C_CREDIT_LIMIT float32
	var c_C_DISCOUNT float32
	var c_C_BALANCE float32
	var c_C_YTD_PAYMENT float32
	var c_C_PAYMENT_CNT float32
	var c_C_DELIVERY_CNT float32
	var c_C_DATA string
	var _tmp402 float32
	var _tmp403 float32
	var _tmp404 float32
	var _tmp405 bool
	var _tmp406 string
	var _tmp407 string
	var _tmp408 string
	var _tmp409 string
	var _tmp410 string
	var _tmp411 string
	var _tmp412 string
	var _tmp413 string
	var _tmp414 string
	var _tmp415 string
	var _tmp416 string
	var _tmp417 string
	var _tmp418 string
	var _tmp419 string
	var _tmp420 string
	var _tmp421 string
	var _tmp422 string
	var _tmp423 string

	var keyBytes1 []byte
	var row1 Customer
	var keyBytes2 []byte
	var row2 Customer

	w_id = toUint64(params["w_id"])
	d_id = toUint64(params["d_id"])
	c_w_id = toUint64(params["c_w_id"])
	c_d_id = toUint64(params["c_d_id"])
	c_id = toUint64(params["c_id"])
	amount = toFloat32(params["amount"])

	goto BB134

BB134:
	// Optimized combined table access: Customer
	keyBytes1, row1 = getCustomer(tx, CustomerKey{C_W_ID: c_w_id, C_D_ID: c_d_id, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes1)
	c_C_CREDIT = row1.C_CREDIT
	c_C_DATA = row1.C_DATA
	c_C_PHONE = row1.C_PHONE
	c_C_STATE = row1.C_STATE
	c_C_FIRST = row1.C_FIRST
	c_C_PAYMENT_CNT = row1.C_PAYMENT_CNT
	c_C_CITY = row1.C_CITY
	c_C_SINCE = row1.C_SINCE
	c_C_STREET_2 = row1.C_STREET_2
	c_C_MIDDLE = row1.C_MIDDLE
	c_C_YTD_PAYMENT = row1.C_YTD_PAYMENT
	c_C_W_ID = row1.Key.C_W_ID
	c_C_CREDIT_LIMIT = row1.C_CREDIT_LIMIT
	c_C_ID = row1.Key.C_ID
	c_C_D_ID = row1.Key.C_D_ID
	c_C_LAST = row1.C_LAST
	c_C_ZIP = row1.C_ZIP
	c_C_DELIVERY_CNT = row1.C_DELIVERY_CNT
	c_C_DISCOUNT = row1.C_DISCOUNT
	c_C_BALANCE = row1.C_BALANCE
	c_C_STREET_1 = row1.C_STREET_1
	_tmp402 = c_C_BALANCE - amount
	c_C_BALANCE = _tmp402
	_tmp403 = c_C_YTD_PAYMENT + amount
	c_C_YTD_PAYMENT = _tmp403
	_tmp404 = c_C_PAYMENT_CNT + 1
	c_C_PAYMENT_CNT = _tmp404
	_tmp405 = c_C_CREDIT == "BC"
	if _tmp405 {
		goto BB135
	} else {
		goto BB136
	}
BB135:
	_tmp406 = fromUint64(c_C_ID)
	_tmp407 = concat(_tmp406, " ")
	_tmp408 = fromUint64(c_C_D_ID)
	_tmp409 = concat(_tmp407, _tmp408)
	_tmp410 = concat(_tmp409, " ")
	_tmp411 = fromUint64(c_C_W_ID)
	_tmp412 = concat(_tmp410, _tmp411)
	_tmp413 = concat(_tmp412, " ")
	_tmp414 = fromUint64(d_id)
	_tmp415 = concat(_tmp413, _tmp414)
	_tmp416 = concat(_tmp415, " ")
	_tmp417 = fromUint64(w_id)
	_tmp418 = concat(_tmp416, _tmp417)
	_tmp419 = concat(_tmp418, " ")
	_tmp420 = fromFloat32(amount)
	_tmp421 = concat(_tmp419, _tmp420)
	_tmp422 = concat(_tmp421, " | ")
	_tmp423 = concat(_tmp422, c_C_DATA)
	c_C_DATA = _tmp423
	goto BB136
BB136:
	// Optimized combined table access: Customer
	keyBytes2, row2 = getCustomer(tx, CustomerKey{C_W_ID: c_w_id, C_D_ID: c_d_id, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes2)
	row2.C_CREDIT = c_C_CREDIT
	row2.C_DATA = c_C_DATA
	row2.C_PHONE = c_C_PHONE
	row2.C_STATE = c_C_STATE
	row2.C_FIRST = c_C_FIRST
	row2.C_PAYMENT_CNT = c_C_PAYMENT_CNT
	row2.C_CITY = c_C_CITY
	row2.C_SINCE = c_C_SINCE
	row2.C_STREET_2 = c_C_STREET_2
	row2.C_MIDDLE = c_C_MIDDLE
	row2.C_YTD_PAYMENT = c_C_YTD_PAYMENT
	row2.Key.C_W_ID = c_C_W_ID
	row2.C_CREDIT_LIMIT = c_C_CREDIT_LIMIT
	row2.Key.C_ID = c_C_ID
	row2.Key.C_D_ID = c_C_D_ID
	row2.C_LAST = c_C_LAST
	row2.C_ZIP = c_C_ZIP
	row2.C_DELIVERY_CNT = c_C_DELIVERY_CNT
	row2.C_DISCOUNT = c_C_DISCOUNT
	row2.C_BALANCE = c_C_BALANCE
	row2.C_STREET_1 = c_C_STREET_1
	putCustomer(tx, CustomerKey{C_W_ID: c_w_id, C_D_ID: c_d_id, C_ID: c_id}, row2)
	return &proto.TrxRes{
		Status: proto.Status_Success,
		Info:   in.Info,
		RWSets: rwSet,
	}, nil
}

// PaymentHop0Par calculates the partition for hop 0 without database access.
func PaymentHop0Par(params map[string]string) uint64 {
	var w_id uint64
	var amount float32
	var _tmp397 float32
	var _tmp398 float32

	var keyBytes1 []byte
	var row1 Warehouse
	var keyBytes2 []byte
	var row2 Warehouse

	w_id = toUint64(params["w_id"])
	amount = toFloat32(params["amount"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB132

BB132:
	// First table access - calculate partition: Warehouse
	if true { return getWarehousePar(WarehouseKey{W_ID: w_id}) }
	// TableGet: Warehouse
	keyBytes1, row1 = getWarehouse(tx, WarehouseKey{W_ID: w_id})
	rwSet = AddRWSet(rwSet, "Warehouse", keyBytes1)
	_tmp397 = row1.W_YTD
	_tmp398 = _tmp397 + amount
	// First table access - calculate partition: Warehouse
	if true { return putWarehousePar(WarehouseKey{W_ID: w_id}) }
	// TableSet: Warehouse
	keyBytes2, row2 = getWarehouse(tx, WarehouseKey{W_ID: w_id})
	rwSet = AddRWSet(rwSet, "Warehouse", keyBytes2)
	row2.W_YTD = _tmp398
	putWarehouse(tx, WarehouseKey{W_ID: w_id}, row2)
	panic("unexpected hop exit in partition")
}

// PaymentHop1Par calculates the partition for hop 1 without database access.
func PaymentHop1Par(params map[string]string) uint64 {
	var w_id uint64
	var d_id uint64
	var amount float32
	var _tmp399 float32
	var _tmp400 float32

	var keyBytes1 []byte
	var row1 District
	var keyBytes2 []byte
	var row2 District

	w_id = toUint64(params["w_id"])
	d_id = toUint64(params["d_id"])
	amount = toFloat32(params["amount"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB133

BB133:
	// First table access - calculate partition: District
	if true { return getDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: d_id}) }
	// TableGet: District
	keyBytes1, row1 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id})
	rwSet = AddRWSet(rwSet, "District", keyBytes1)
	_tmp399 = row1.D_YTD
	_tmp400 = _tmp399 + amount
	// First table access - calculate partition: District
	if true { return putDistrictPar(DistrictKey{D_W_ID: w_id, D_ID: d_id}) }
	// TableSet: District
	keyBytes2, row2 = getDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id})
	rwSet = AddRWSet(rwSet, "District", keyBytes2)
	row2.D_YTD = _tmp400
	putDistrict(tx, DistrictKey{D_W_ID: w_id, D_ID: d_id}, row2)
	panic("unexpected hop exit in partition")
}

// PaymentHop2Par calculates the partition for hop 2 without database access.
func PaymentHop2Par(params map[string]string) uint64 {
	var w_id uint64
	var d_id uint64
	var c_w_id uint64
	var c_d_id uint64
	var c_id uint64
	var amount float32
	var c_C_W_ID uint64
	var c_C_D_ID uint64
	var c_C_ID uint64
	var c_C_FIRST string
	var c_C_MIDDLE string
	var c_C_LAST string
	var c_C_STREET_1 string
	var c_C_STREET_2 string
	var c_C_CITY string
	var c_C_STATE string
	var c_C_ZIP string
	var c_C_PHONE string
	var c_C_SINCE uint64
	var c_C_CREDIT string
	var c_C_CREDIT_LIMIT float32
	var c_C_DISCOUNT float32
	var c_C_BALANCE float32
	var c_C_YTD_PAYMENT float32
	var c_C_PAYMENT_CNT float32
	var c_C_DELIVERY_CNT float32
	var c_C_DATA string
	var _tmp402 float32
	var _tmp403 float32
	var _tmp404 float32
	var _tmp405 bool
	var _tmp406 string
	var _tmp407 string
	var _tmp408 string
	var _tmp409 string
	var _tmp410 string
	var _tmp411 string
	var _tmp412 string
	var _tmp413 string
	var _tmp414 string
	var _tmp415 string
	var _tmp416 string
	var _tmp417 string
	var _tmp418 string
	var _tmp419 string
	var _tmp420 string
	var _tmp421 string
	var _tmp422 string
	var _tmp423 string

	var keyBytes1 []byte
	var row1 Customer
	var keyBytes2 []byte
	var row2 Customer

	w_id = toUint64(params["w_id"])
	d_id = toUint64(params["d_id"])
	c_w_id = toUint64(params["c_w_id"])
	c_d_id = toUint64(params["c_d_id"])
	c_id = toUint64(params["c_id"])
	amount = toFloat32(params["amount"])

	var tx *bolt.Tx = nil // Fake tx for unreachable code
	var rwSet []*proto.RWSet // Fake rwSet for unreachable code
	_ = tx // Suppress unused variable warning
	_ = rwSet // Suppress unused variable warning

	goto BB134

BB134:
	// First table access (optimized group) - calculate partition: Customer
	if true { return getCustomerPar(CustomerKey{C_W_ID: c_w_id, C_D_ID: c_d_id, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes1, row1 = getCustomer(tx, CustomerKey{C_W_ID: c_w_id, C_D_ID: c_d_id, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes1)
	c_C_CREDIT = row1.C_CREDIT
	c_C_DATA = row1.C_DATA
	c_C_PHONE = row1.C_PHONE
	c_C_STATE = row1.C_STATE
	c_C_FIRST = row1.C_FIRST
	c_C_PAYMENT_CNT = row1.C_PAYMENT_CNT
	c_C_CITY = row1.C_CITY
	c_C_SINCE = row1.C_SINCE
	c_C_STREET_2 = row1.C_STREET_2
	c_C_MIDDLE = row1.C_MIDDLE
	c_C_YTD_PAYMENT = row1.C_YTD_PAYMENT
	c_C_W_ID = row1.Key.C_W_ID
	c_C_CREDIT_LIMIT = row1.C_CREDIT_LIMIT
	c_C_ID = row1.Key.C_ID
	c_C_D_ID = row1.Key.C_D_ID
	c_C_LAST = row1.C_LAST
	c_C_ZIP = row1.C_ZIP
	c_C_DELIVERY_CNT = row1.C_DELIVERY_CNT
	c_C_DISCOUNT = row1.C_DISCOUNT
	c_C_BALANCE = row1.C_BALANCE
	c_C_STREET_1 = row1.C_STREET_1
	_tmp402 = c_C_BALANCE - amount
	c_C_BALANCE = _tmp402
	_tmp403 = c_C_YTD_PAYMENT + amount
	c_C_YTD_PAYMENT = _tmp403
	_tmp404 = c_C_PAYMENT_CNT + 1
	c_C_PAYMENT_CNT = _tmp404
	_tmp405 = c_C_CREDIT == "BC"
	if _tmp405 {
		goto BB135
	} else {
		goto BB136
	}
BB135:
	_tmp406 = fromUint64(c_C_ID)
	_tmp407 = concat(_tmp406, " ")
	_tmp408 = fromUint64(c_C_D_ID)
	_tmp409 = concat(_tmp407, _tmp408)
	_tmp410 = concat(_tmp409, " ")
	_tmp411 = fromUint64(c_C_W_ID)
	_tmp412 = concat(_tmp410, _tmp411)
	_tmp413 = concat(_tmp412, " ")
	_tmp414 = fromUint64(d_id)
	_tmp415 = concat(_tmp413, _tmp414)
	_tmp416 = concat(_tmp415, " ")
	_tmp417 = fromUint64(w_id)
	_tmp418 = concat(_tmp416, _tmp417)
	_tmp419 = concat(_tmp418, " ")
	_tmp420 = fromFloat32(amount)
	_tmp421 = concat(_tmp419, _tmp420)
	_tmp422 = concat(_tmp421, " | ")
	_tmp423 = concat(_tmp422, c_C_DATA)
	c_C_DATA = _tmp423
	goto BB136
BB136:
	// First table access (optimized group) - calculate partition: Customer
	if true { return putCustomerPar(CustomerKey{C_W_ID: c_w_id, C_D_ID: c_d_id, C_ID: c_id}) }
	// Optimized combined table access: Customer
	keyBytes2, row2 = getCustomer(tx, CustomerKey{C_W_ID: c_w_id, C_D_ID: c_d_id, C_ID: c_id})
	rwSet = AddRWSet(rwSet, "Customer", keyBytes2)
	row2.C_CREDIT = c_C_CREDIT
	row2.C_DATA = c_C_DATA
	row2.C_PHONE = c_C_PHONE
	row2.C_STATE = c_C_STATE
	row2.C_FIRST = c_C_FIRST
	row2.C_PAYMENT_CNT = c_C_PAYMENT_CNT
	row2.C_CITY = c_C_CITY
	row2.C_SINCE = c_C_SINCE
	row2.C_STREET_2 = c_C_STREET_2
	row2.C_MIDDLE = c_C_MIDDLE
	row2.C_YTD_PAYMENT = c_C_YTD_PAYMENT
	row2.Key.C_W_ID = c_C_W_ID
	row2.C_CREDIT_LIMIT = c_C_CREDIT_LIMIT
	row2.Key.C_ID = c_C_ID
	row2.Key.C_D_ID = c_C_D_ID
	row2.C_LAST = c_C_LAST
	row2.C_ZIP = c_C_ZIP
	row2.C_DELIVERY_CNT = c_C_DELIVERY_CNT
	row2.C_DISCOUNT = c_C_DISCOUNT
	row2.C_BALANCE = c_C_BALANCE
	row2.C_STREET_1 = c_C_STREET_1
	putCustomer(tx, CustomerKey{C_W_ID: c_w_id, C_D_ID: c_d_id, C_ID: c_id}, row2)
	return 0
}

func PaymentNextReq(in *proto.TrxRes, params map[string]string, shards int) (*proto.TrxReq, map[string]string, int) {
	hopId := in.Info.Hopid
	req := &proto.TrxReq{Info: in.Info}
	nextShard := 0

	switch hopId {
	case 0:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(PaymentHop0Par(paramsCopy))
	case 1:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(PaymentHop1Par(paramsCopy))
	case 2:
		// Deep copy params to avoid modification
		paramsCopy := make(map[string]string)
		for k, v := range params {
			paramsCopy[k] = v
		}
		// Calculate partition for next hop using partition function
		nextShard = int(PaymentHop2Par(paramsCopy))
	default:
		return nil, params, 0
	}

	req.Params = params
	req.Info.Hopid += 1
	req.Dependency = in.Dependency
	return req, params, nextShard
}

func PaymentChainImpl(db *bolt.DB) *Chain {
	// Create the list of hops
	hops := make([]*Hop, 3)

	hops[0] = &Hop{
		id:         0,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    PaymentHop0,
		conflicts:  map[int32]int32{},
	}

	hops[1] = &Hop{
		id:         1,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    PaymentHop1,
		conflicts:  map[int32]int32{},
	}

	hops[2] = &Hop{
		id:         2,
		hopType:    util.NormalHop,
		isReadOnly: false,
		process:    PaymentHop2,
		conflicts:  map[int32]int32{2: 2},
	}

	// add field names
	return &Chain{db: db, hops: hops, NextReq: PaymentNextReq}
}

func PaymentToJSON(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

